"""Interface-aligned P1 line mesh, generated by gmsh by default."""
import math
import numpy as np


def aligned_mesh(width_um, padding_um, h_um, backend):
    a = width_um/2
    breaks = np.array([-a-padding_um, -a, a, a+padding_um])
    counts = [max(1, math.ceil(d/h_um-1e-12)) for d in np.diff(breaks)]
    if backend == 'native':
        x = np.concatenate([np.linspace(l,r,c+1)[:-1] for l,r,c in
                            zip(breaks[:-1],breaks[1:],counts)] + [breaks[-1:]])
        return x, np.array([np.arange(len(x)-1), np.arange(1,len(x))])
    import gmsh
    if gmsh.isInitialized():
        raise RuntimeError('gmsh is already initialized; use native backend or a separate process.')
    gmsh.initialize(['waveoptics-m1', '-nopopup'], readConfigFiles=False)
    try:
        gmsh.option.setNumber('General.Terminal', 0)
        gmsh.option.setNumber('General.NumThreads', 1)
        gmsh.model.add('slab-m1')
        pts = [gmsh.model.geo.addPoint(float(x),0,0) for x in breaks]
        lines = [gmsh.model.geo.addLine(pts[i],pts[i+1]) for i in range(3)]
        gmsh.model.geo.synchronize()
        for tag, count in zip(lines,counts):
            gmsh.model.mesh.setTransfiniteCurve(tag,count+1)
        gmsh.model.mesh.generate(1)
        tags, coords, _ = gmsh.model.mesh.getNodes()
        coord_x = coords.reshape(-1,3)[:,0]
        permutation = np.argsort(coord_x)
        x = coord_x[permutation]
        index = {int(tag):i for i,tag in enumerate(tags[permutation])}
        types, _, node_lists = gmsh.model.mesh.getElements(1)
        cells = []
        for element_type, node_list in zip(types,node_lists):
            if element_type != 1:
                raise RuntimeError('Expected gmsh 2-node line elements.')
            cells.extend([[index[int(l)],index[int(r)]] for l,r in node_list.reshape(-1,2)])
        t = np.asarray(cells,dtype=int).T
        t.sort(axis=0)
        t = t[:,np.argsort(t[0])]
        # Preserve material interfaces exactly (gmsh uses floating-point CAD).
        for b in breaks:
            i = np.argmin(abs(x-b))
            if abs(x[i]-b) > 1e-10*max(1,abs(b)):
                raise RuntimeError('Missing material interface node.')
            x[i] = b
        if not np.array_equal(t, np.array([np.arange(len(x)-1),np.arange(1,len(x))])):
            raise RuntimeError('gmsh line mesh is not a connected ordered interval.')
        return x,t
    finally:
        gmsh.finalize()
