'use strict';
const $=id=>document.getElementById(id);
const I18N={
  ko:{title:'DC BOM Designer v4.1',subtitle:'공개 UI + 비공개 계산 엔진 + Rack/Cooling/Optical 시각화',security:'핵심 계산식과 제품 매칭 로직은 비공개 백엔드에서 실행되며, GitHub Pages에는 입력 UI와 결과 표시 코드만 배포합니다.',requirements:'요구조건',gpu:'필요 GPU',system:'시스템',topology:'토폴로지',protocol:'Fabric 프로토콜',tier:'조달 정책',facility:'Facility / Storage 옵션',rackOps:'Rack / IT 운영 보조장비',run:'설계 계산',result:'설계 결과',fabric:'Fabric / Optical',bom:'Generic BOM',receipt:'제품 매칭 예상 영수증',receiptNote:'업체별 부품 리스트의 등록 제품에서 현재 설계 조건과 맞는 제조사·모델·제한된 대안을 선택합니다. 정확한 SKU가 없으면 RFQ로 유지합니다.',rackDiagram:'Rack 구성 해설도',rackDiagramNote:'현재 BOM을 기준으로 대표 Rack의 네트워크/컴퓨트/스토리지/전원 계층을 보여줍니다. 실제 시공 RU 배치는 프로젝트별 재검토가 필요합니다.',coolingDiagram:'Cooling architecture',opticalGuide:'Optical / Interconnect 선택 가이드',coverage:'BOM Coverage Matrix',coverageNote:'현재 설계가 일반 데이터센터 rack 구성요소 중 무엇을 직접 계산하고, 무엇을 옵션/RFQ로 다루는지 표시합니다.'},
  en:{title:'DC BOM Designer v4.1',subtitle:'Public UI + private engine + rack/cooling/optical visualization',security:'Source remains in the private repository; the generated GitHub Pages browser runtime calculates locally.',requirements:'Requirements',gpu:'Required GPUs',system:'System',topology:'Topology',protocol:'Fabric protocol',tier:'Procurement policy',facility:'Facility / Storage options',rackOps:'Rack / IT operations accessories',run:'Calculate design',result:'Design result',fabric:'Fabric / Optical',bom:'Generic BOM',receipt:'Estimated product bill',receiptNote:'Products match the calculation profile. Unverified compatibility, exact SKUs and prices require RFQ.',rackDiagram:'Rack component diagram',rackDiagramNote:'A representative rack view derived from the current BOM. Final construction RU placement must be reviewed per project.',coolingDiagram:'Cooling architecture',opticalGuide:'Optical / Interconnect selection guide',coverage:'BOM Coverage Matrix',coverageNote:'Shows which common data-center rack components are calculated directly and which remain optional or RFQ-driven.'},
  ja:{title:'DC BOM Designer v4.1',subtitle:'公開UI + 非公開計算エンジン + Rack/Cooling/Optical可視化',security:'元のソースは非公開リポジトリに保持され、GitHub Pagesでは生成済みブラウザランタイムがローカル計算します。',requirements:'要件',gpu:'必要GPU数',system:'システム',topology:'トポロジ',protocol:'Fabricプロトコル',tier:'調達方針',facility:'Facility / Storage オプション',rackOps:'Rack / IT運用補助機器',run:'設計計算',result:'設計結果',fabric:'Fabric / Optical',bom:'Generic BOM',receipt:'製品マッチング概算明細',receiptNote:'製品DB全体や内部スコアはブラウザへ送らず、選定品と限定的な代替候補のみ返します。',rackDiagram:'Rack構成解説図',rackDiagramNote:'現在のBOMを基に代表Rackのネットワーク/Compute/Storage/電源レイヤを示します。最終RU配置は案件ごとに再確認してください。',coolingDiagram:'Cooling architecture',opticalGuide:'Optical / Interconnect選定ガイド',coverage:'BOM Coverage Matrix',coverageNote:'一般的なデータセンターrack構成要素のうち、直接計算する項目とオプション/RFQ項目を示します。'},
  zh:{title:'DC BOM Designer v4.1',subtitle:'公开 UI + 私有计算引擎 + Rack/Cooling/Optical 可视化',security:'源代码保留在私有仓库中；GitHub Pages 使用生成的浏览器运行时在本地计算。',requirements:'需求条件',gpu:'所需 GPU',system:'系统',topology:'拓扑',protocol:'Fabric 协议',tier:'采购策略',facility:'Facility / Storage 选项',rackOps:'Rack / IT 运维辅助设备',run:'计算设计',result:'设计结果',fabric:'Fabric / Optical',bom:'通用 BOM',receipt:'产品匹配预计清单',receiptNote:'不会把完整产品数据库或内部评分发送到浏览器，只返回选定产品和有限的替代项。',rackDiagram:'Rack 组件示意图',rackDiagramNote:'根据当前 BOM 展示代表性 Rack 的网络/计算/存储/供电层级。最终施工 RU 布置需按项目复核。',coolingDiagram:'Cooling architecture',opticalGuide:'Optical / Interconnect 选择指南',coverage:'BOM Coverage Matrix',coverageNote:'显示常见数据中心 Rack 组件中哪些由引擎直接计算，哪些作为可选项或 RFQ 处理。'},
  de:{title:'DC BOM Designer v4.1',subtitle:'Öffentliche UI + private Engine + Rack/Cooling/Optical-Visualisierung',security:'Der Quellcode bleibt im privaten Repository; die generierte GitHub-Pages-Laufzeit berechnet lokal im Browser.',requirements:'Anforderungen',gpu:'Benötigte GPUs',system:'System',topology:'Topologie',protocol:'Fabric-Protokoll',tier:'Beschaffungsstrategie',facility:'Facility-/Storage-Optionen',rackOps:'Rack-/IT-Betriebszubehör',run:'Entwurf berechnen',result:'Entwurfsergebnis',fabric:'Fabric / Optical',bom:'Generische BOM',receipt:'Geschätzte Produktliste',receiptNote:'Die vollständige Produktdatenbank und interne Scores werden nicht an den Browser gesendet; zurückgegeben werden nur ausgewählte Produkte und begrenzte Alternativen.',rackDiagram:'Rack-Komponentendiagramm',rackDiagramNote:'Repräsentative Rack-Ansicht aus der aktuellen BOM. Die endgültige RU-Platzierung muss projektspezifisch geprüft werden.',coolingDiagram:'Cooling architecture',opticalGuide:'Optical-/Interconnect-Auswahlhilfe',coverage:'BOM Coverage Matrix',coverageNote:'Zeigt, welche üblichen Rechenzentrums-Rack-Komponenten direkt berechnet und welche optional/RFQ-basiert behandelt werden.'}
};
let lang='ko';
function setLang(l){lang=l;document.documentElement.lang=l;document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));document.querySelectorAll('[data-i18n]').forEach(e=>{const k=e.dataset.i18n;if(I18N[l]?.[k])e.textContent=I18N[l][k];});localStorage.setItem('dcBomLang',l)}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));setLang(localStorage.getItem('dcBomLang')||'ko');
function payload(){const v=id=>$(id).value,n=id=>v(id).trim()===''?null:Number(v(id));return {targetGPU:n('targetGPU'),systemId:v('systemId'),topology:v('topology'),fabricProtocol:v('fabricProtocol'),procurementTier:v('procurementTier'),podLeafLimit:n('podLeafLimit'),targetPodEgress:n('targetPodEgress'),rackRU:n('rackRU'),rackPowerKw:n('rackPowerKw'),rackCoolingKw:n('rackCoolingKw'),coolingMode:v('coolingMode'),serverDistanceM:n('serverDistanceM'),leafSpineDistanceM:n('leafSpineDistanceM'),serverCabling:v('serverCabling'),leafSpineCabling:v('leafSpineCabling'),trunkFiberCount:n('trunkFiberCount'),sparePct:n('sparePct'),facilityEnabled:$('facilityEnabled').checked,facilityRedundancy:v('facilityRedundancy'),storageEnabled:$('storageEnabled').checked,storageCapacityTb:n('storageCapacityTb'),storageProtocol:v('storageProtocol'),storageEndpointPorts:n('storageEndpointPorts'),enterpriseRackEnabled:$('enterpriseRackEnabled').checked,firewallQty:n('firewallQty'),routerQty:n('routerQty'),loadBalancerQty:n('loadBalancerQty'),kvmQty:n('kvmQty'),nasQty:n('nasQty'),...window.getEngineeringInputs()};}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function kpi(label,val){return `<div class="kpi"><div class="v">${esc(val)}</div><div class="l">${esc(label)}</div></div>`}
function drawTopology(r){const svg=$('topologySvg');if(!r.usable){svg.innerHTML='';return;}const f=r.fabric,s=r.summary;const nodes=[['Compute',80,105,s.computeRacks+' rack'],['Leaf',300,105,f.leafCount+' sw'],['Spine',520,105,f.spineCount+' sw']];if(f.coreCount)nodes.push(['Core',740,105,f.coreCount+' sw']);let out='';for(let i=0;i<nodes.length-1;i++){out+=`<line x1="${nodes[i][1]+110}" y1="130" x2="${nodes[i+1][1]}" y2="130" stroke="#6ea8ff" stroke-width="5"/>`;}for(const [name,x,y,val] of nodes){out+=`<rect x="${x}" y="${y}" width="110" height="50" rx="9" fill="#172641" stroke="#4d6f9f"/><text x="${x+55}" y="${y+20}" text-anchor="middle" fill="#fff" font-size="12" font-weight="800">${name}</text><text x="${x+55}" y="${y+39}" text-anchor="middle" fill="#9fb1ce" font-size="10">${val}</text>`;}svg.innerHTML=out;}
function drawRack(r){const svg=$('rackSvg'),legend=$('rackLegend');if(!r.usable){svg.innerHTML='';legend.innerHTML='';return;}const L=r.rackLayout, rackX=310,rackY=35,rackW=300,rackH=560,ruH=rackH/L.rackRU;let out=`<rect x="${rackX}" y="${rackY}" width="${rackW}" height="${rackH}" rx="10" fill="#0c1322" stroke="#6b7d98" stroke-width="4"/><text x="460" y="24" text-anchor="middle" fill="#fff" font-size="18" font-weight="900">Representative ${L.rackRU}U Rack</text>`;
  for(let u=0;u<=L.rackRU;u+=4){const y=rackY+rackH-u*ruH;out+=`<line x1="${rackX-10}" y1="${y}" x2="${rackX}" y2="${y}" stroke="#7487a6"/><text x="${rackX-16}" y="${y+4}" text-anchor="end" fill="#8ea1be" font-size="9">${u}U</text>`;}
  const palette={Network:'#376fd0',Patch:'#7b5fd2',Compute:'#1d6f5d',Storage:'#8152a5',Power:'#a9791d',Ops:'#a74848',Cable:'#56647a'};
  for(const c of L.components){const y=rackY+rackH-c.endU*ruH,h=Math.max(14,(c.endU-c.startU+1)*ruH-2);out+=`<rect x="${rackX+18}" y="${y}" width="${rackW-36}" height="${h}" rx="5" fill="${palette[c.group]||'#3a506e'}" opacity=".95"/><text x="${rackX+30}" y="${y+Math.min(22,h/2+5)}" fill="#fff" font-size="12" font-weight="800">${esc(c.label)}</text><text x="${rackX+rackW-28}" y="${y+Math.min(22,h/2+5)}" text-anchor="end" fill="#eaf2ff" font-size="10">${c.startU}-${c.endU}U</text>`;}
  out+=`<rect x="${rackX-24}" y="${rackY+50}" width="12" height="${rackH-100}" rx="5" fill="#cf5252"/><rect x="${rackX+rackW+12}" y="${rackY+50}" width="12" height="${rackH-100}" rx="5" fill="#437bd4"/><text x="${rackX-18}" y="${rackY+42}" text-anchor="middle" fill="#ff9d9d" font-size="10">PDU A</text><text x="${rackX+rackW+18}" y="${rackY+42}" text-anchor="middle" fill="#94baff" font-size="10">PDU B</text>`;
  svg.innerHTML=out;legend.innerHTML=L.notes.map(n=>`<div class="legendCard"><b>${esc(n.title)}</b><span>${esc(n.text)}</span></div>`).join('');}
let coolingScenario='normal';
function drawCooling(r){const svg=$('coolingSvg'),notes=$('coolingNotes');if(!r.usable){svg.innerHTML='';notes.innerHTML='';return;}const c=r.cooling,fault=coolingScenario==='fault';const defs=`<defs><linearGradient id="coolBg" x2="0" y2="1"><stop stop-color="${fault?'#321d28':'#10243b'}"/><stop offset="1" stop-color="#091522"/></linearGradient><linearGradient id="rackFace"><stop stop-color="#315b8c"/><stop offset="1" stop-color="#132b4d"/></linearGradient><filter id="glow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter><style>.flow{stroke-dasharray:12 9;animation:flow 1.5s linear infinite}.flow.slow{animation-duration:2.7s}.faultflow{stroke-dasharray:3 18;animation:flow 3.8s linear infinite;opacity:.55}.blink{animation:blink 1.4s ease-in-out infinite}.alarm{animation:alarm .75s ease-in-out infinite}.fan{transform-box:fill-box;transform-origin:center;animation:${fault?'none':'spin 1.6s linear infinite'}}@keyframes flow{to{stroke-dashoffset:-42}}@keyframes blink{50%{opacity:.28}}@keyframes alarm{50%{opacity:.2}}@keyframes spin{to{transform:rotate(360deg)}}text{font-family:Arial,'Malgun Gothic',sans-serif}</style></defs>`;const bg=`<rect width="900" height="360" rx="14" fill="url(#coolBg)"/><path d="M28 292H872" stroke="#253c55" stroke-width="2"/><text x="30" y="30" fill="${fault?'#ffb1a9':'#dcecff'}" font-size="16" font-weight="900">COOLING LOOP · ${esc(c.modeLabel||'AIR')} · ${fault?'FAULT SCENARIO':'NORMAL OPERATION'}</text><text x="30" y="49" fill="${fault?'#ffc58d':'#8fa9c3'}" font-size="11">${fault?'⚠ 펌프 유량 저하 · 환수 온도 상승 · 예비 장치 전환 필요':'열 발생 → 열교환/냉각 → 냉기·냉각수 공급 → 환수'}</text>`;let out=defs+bg;
  const rack=(x,y,label)=>`<g><polygon points="${x},${y} ${x+118},${y-24} ${x+170},${y+4} ${x+52},${y+30}" fill="#3f76a9" stroke="#8bc7ff"/><polygon points="${x},${y} ${x},${y+112} ${x+52},${y+140} ${x+52},${y+30}" fill="#183b64" stroke="#628ebc"/><polygon points="${x+52},${y+30} ${x+170},${y+4} ${x+170},${y+116} ${x+52},${y+140}" fill="url(#rackFace)" stroke="#628ebc"/>${[0,1,2,3].map(i=>`<rect x="${x+65}" y="${y+43+i*20}" width="86" height="12" rx="3" fill="#0d1e35" stroke="#5d8fb9"/><circle cx="${x+74}" cy="${y+49+i*20}" r="3" fill="#65edb0" class="blink"/><circle cx="${x+143}" cy="${y+49+i*20}" r="2" fill="#68b9ff"/>`).join('')}<text x="${x+85}" y="${y+162}" fill="#dcecff" font-size="11" text-anchor="middle" font-weight="800">${label}</text><text x="${x+85}" y="${y+177}" fill="#8fa9c3" font-size="10" text-anchor="middle">${esc(c.rackDensityKw+' kW')}</text></g>`;
  out+=rack(70,135,'COMPUTE RACK A')+rack(70,245,'COMPUTE RACK B');
  if(c.mode==='air'){out+=`<g><rect x="470" y="103" width="190" height="145" rx="14" fill="#22364e" stroke="${fault?'#e77b68':'#89a9ca'}"/><text x="565" y="130" fill="#fff" font-size="15" font-weight="900" text-anchor="middle">CRAH / HVAC</text><text x="565" y="151" fill="#b9cce2" font-size="10" text-anchor="middle">${fault?'팬 정지 · 고온 알람':'냉각 코일 · 팬 · 필터'}</text><g class="fan" fill="none" stroke="#9cc8ec" stroke-width="3">${[0,60,120,180,240,300].map(a=>`<path d="M565 188 l0 -24" transform="rotate(${a} 565 188)"/>`).join('')}</g><circle cx="565" cy="188" r="27" fill="#10243b" stroke="#80b6e0"/><circle cx="565" cy="188" r="7" fill="${fault?'#ff6f61':'#6ee4ff'}" class="${fault?'alarm':'blink'}"/><rect x="510" y="220" width="110" height="9" rx="4" fill="${fault?'#d64f49':'#64b5f6'}" class="${fault?'alarm':'blink'}"/></g><path d="M230 166 C315 110 390 112 470 152" fill="none" stroke="#ef7068" stroke-width="10" class="${fault?'faultflow':'flow'}" filter="url(#glow)"/><path d="M470 206 C380 260 310 264 230 278" fill="none" stroke="#5db9ff" stroke-width="10" class="${fault?'faultflow':'flow'}" filter="url(#glow)"/><text x="340" y="100" fill="#ffaaa4" font-size="12" text-anchor="middle">HOT AIR RETURN</text><text x="350" y="300" fill="#9bd5ff" font-size="12" text-anchor="middle">COOL AIR SUPPLY</text>`;}
  else {out+=`<g><rect x="470" y="95" width="175" height="150" rx="14" fill="#124c62" stroke="${fault?'#e77b68':'#65d4e2'}"/><text x="557" y="124" fill="#fff" font-size="15" font-weight="900" text-anchor="middle">CDU</text><text x="557" y="145" fill="#bcebf1" font-size="10" text-anchor="middle">${fault?'펌프 유량 저하 · 알람':'펌프 · 열교환기 · 센서'}</text><rect x="520" y="165" width="75" height="45" rx="7" fill="#0a2b3d" stroke="#67d6e2"/><path d="M532 188h50" stroke="${fault?'#e67d6b':'#54e9ff'}" stroke-width="4" class="${fault?'faultflow':'flow'}"/><circle cx="615" cy="177" r="5" fill="${fault?'#ff6f61':'#65efb1'}" class="${fault?'alarm':'blink'}"/><circle cx="615" cy="197" r="5" fill="${fault?'#ff6f61':'#65efb1'}" class="${fault?'alarm':'blink'}"/></g><g><rect x="735" y="100" width="130" height="140" rx="14" fill="#263d55" stroke="#8aa6c5"/><text x="800" y="130" fill="#fff" font-size="13" font-weight="900" text-anchor="middle">CHILLER PLANT</text><path d="M770 170h60M770 185h60M770 200h60" stroke="#7ed9ec" stroke-width="5" class="blink"/><text x="800" y="225" fill="#aac0d5" font-size="10" text-anchor="middle">시설수 · 열 방출</text></g><path d="M230 166 C320 120 390 120 470 160" fill="none" stroke="#3bd4ff" stroke-width="9" class="${fault?'faultflow':'flow'}" filter="url(#glow)"/><path d="M470 210 C380 260 315 264 230 278" fill="none" stroke="#f17c6d" stroke-width="9" class="${fault?'faultflow':'flow'}" filter="url(#glow)"/><path d="M645 160 L735 160" fill="none" stroke="#3bd4ff" stroke-width="9" class="${fault?'faultflow':'flow'}"/><path d="M735 210 L645 210" fill="none" stroke="#f17c6d" stroke-width="9" class="${fault?'faultflow':'flow'}"/><text x="345" y="100" fill="#9beaff" font-size="12" text-anchor="middle">SUPPLY · 냉각수 공급</text><text x="350" y="300" fill="#ffaaa4" font-size="12" text-anchor="middle">RETURN · 열 흡수 후 환수</text>`;}
  out+=`<g transform="translate(30 325)"><circle cx="0" cy="0" r="5" fill="${fault?'#ff6f61':'#65efb1'}" class="${fault?'alarm':''}"/><text x="12" y="4" fill="#a7bfd8" font-size="10">${fault?'장애 감지':'정상 순환'}</text><circle cx="100" cy="0" r="5" fill="#ffd36e" class="blink"/><text x="112" y="4" fill="#a7bfd8" font-size="10">센서 감시</text></g>`;svg.innerHTML=out;notes.innerHTML=c.notes.map(n=>`<div class="legendCard"><b>${esc(n.title)}</b><span>${esc(n.text)}</span></div>`).join('');const bar=$('coolingScenarioBar'),status=$('coolingScenarioStatus');if(bar){bar.classList.toggle('fault',fault);bar.querySelectorAll('[data-cooling-scenario]').forEach(b=>{b.classList.toggle('active',b.dataset.coolingScenario===coolingScenario);b.onclick=()=>{coolingScenario=b.dataset.coolingScenario;drawCooling(window.DCDesign)}});if(status)status.textContent=fault?'문제 발생 · 대응 필요':'정상 작동 · 냉각 순환 중';}}
function renderOpticalGuide(r){const el=$('opticalGuideCards');if(!r.usable){el.innerHTML='';return;}const cards=r.interconnectGuide.map(x=>`<div class="guideCard"><div class="speed">${esc(x.speed)}</div><div class="media">${esc(x.media)}</div><div><b>Distance</b> ${esc(x.distanceM)} m</div><div><b>Connector</b> ${esc(x.connector)}</div><div><b>Rule</b> ${esc(x.rule)}</div><div class="chip">${esc(x.segment)}</div></div>`).join('');el.innerHTML=cards;}
function renderCoverage(r){const el=$('coverageGrid');if(!r.usable){el.innerHTML='';return;}el.innerHTML=r.coverage.map(x=>`<div class="coverageItem ${esc(x.statusClass)}"><div class="coverageHead"><b>${esc(x.item)}</b><span>${esc(x.status)}</span></div><p>${esc(x.note)}</p></div>`).join('');}
function renderProductReceipt(r){
  const body=$('productBody'),status=$('catalogMatchReceiptStatus');if(!body)return;
  const s=r.catalogMatchSummary;if(status)status.textContent=s?`카탈로그 기반 매칭 ${s.matched}/${s.total} · RFQ/엔진 유지 ${s.rfq} · 전체 DB를 로드하지 않고 관련 제품군만 조회`:'카탈로그 매칭 정보 없음';
  body.innerHTML=(r.products||[]).map(x=>{const product=x.source?`<a href="${esc(x.source)}" target="_blank" rel="noopener">${esc(x.product)}</a>`:esc(x.product);return `<tr><td>${esc(x.category)}</td><td>${esc(x.vendor)}</td><td>${product}</td><td>${esc(x.model)}</td><td>${esc(x.qty)}</td><td>${esc((x.alternatives||[]).join(' / ')||'—')}</td></tr>`}).join('');
}
function renderBase(r){window.DCDesign=r;window.DCDesignStale=false;window.currentDesignSnapshot={inputs:r.input||{},results:r,bom:r.bom||[]};$('error').textContent='';const st=$('status');st.textContent=r.status;st.className='status '+(r.status==='READY'?'ready':'review');if(r.usable)$('error').textContent=(r.warnings||[]).join(' · ');if(!r.usable){st.textContent=r.status||'REVIEW';$('error').textContent=(r.reasons||[r.error]).filter(Boolean).join(' · ');$('kpis').innerHTML='';$('fabricDetail').innerHTML='';$('bomBody').innerHTML='';$('productBody').innerHTML='';drawTopology(r);drawRack(r);drawCooling(r);renderOpticalGuide(r);renderCoverage(r);return;}if(r.input?.scenario==='colo'){const s=r.summary;$('kpis').innerHTML=kpi('Tenant racks',s.totalRacks)+kpi('IT capacity',s.totalItPowerKw+' kW')+kpi('Facility scenario',r.facility.facilityPowerKw+' kW');for(const id of ['topologySvg','rackSvg','rackLegend','coolingSvg','coolingNotes','opticalGuideCards','fabricDetail','coverageGrid','productBody'])$(id).innerHTML='';$('bomBody').innerHTML=r.bom.map(x=>`<tr><td>${esc(x.category)}</td><td>${esc(x.item)}</td><td>${esc(x.qty)}</td><td>${esc(x.unit)}</td><td>${esc(x.basis)}</td></tr>`).join('');return;}const s=r.summary,f=r.fabric;$('kpis').innerHTML=kpi('GPU',s.targetGPU)+kpi('Systems',s.systemUnits)+kpi('Compute racks',s.computeRacks)+kpi('IT power',s.totalItPowerKw+' kW')+kpi('Leaf',f.leafCount)+kpi('Spine',f.spineCount)+kpi('Core',f.coreCount)+kpi('Cooling',r.cooling.modeLabel);drawTopology(r);drawRack(r);drawCooling(r);renderOpticalGuide(r);renderCoverage(r);renderFabricDetail(r);$('bomBody').innerHTML=r.bom.map(x=>`<tr><td>${esc(x.category)}</td><td>${esc(x.item)}</td><td>${esc(x.qty)}</td><td>${esc(x.unit)}</td><td>${esc(x.basis||'Calculated')}</td></tr>`).join('');renderProductReceipt(r);}

function renderFabricDetail(r){if(!r.usable||r.input?.scenario==='colo'){$('fabricDetail').innerHTML='';return;}const f=r.fabric;$('fabricDetail').innerHTML=`<div class="detailGrid"><div class="detail"><b>Switch</b><span>${esc(f.switchName)}</span></div><div class="detail"><b>Server media</b><span>${esc(f.serverFacingMedia)}</span></div><div class="detail"><b>Leaf↔Spine media</b><span>${esc(f.leafSpineMedia)}</span></div><div class="detail"><b>Spine ports</b><span>${f.spineDownPortsUsed||0} down + ${f.coreUplinkPorts||0} core + ${f.spineUnusedPorts??0} unused</span></div><div class="detail"><b>Server loss</b><span>${r.optical.server.loss.applicable?r.optical.server.loss.estimatedDb+' / '+r.optical.server.loss.budgetDb+' dB':'N/A'}</span></div><div class="detail"><b>Leaf↔Spine loss</b><span>${r.optical.leafSpine.loss.applicable?r.optical.leafSpine.loss.estimatedDb+' / '+r.optical.leafSpine.loss.budgetDb+' dB':'N/A'}</span></div><div class="detail"><b>Server trunks</b><span>${r.optical.server.trunk.cableCount}</span></div><div class="detail"><b>Leaf↔Spine trunks</b><span>${r.optical.leafSpine.trunk.cableCount}</span></div></div>`;}
function refreshDesignDetails(r=window.DCDesign){if(!r)return;if(r.input?.scenario==='colo'){for(const id of ['rackSvg','rackLegend','coolingSvg','coolingNotes','opticalGuideCards','fabricDetail'])$(id).innerHTML='';return;}drawRack(r);drawCooling(r);renderOpticalGuide(r);renderFabricDetail(r);}
window.DCRefreshDetails=refreshDesignDetails;
async function render(r){if(window.DCCatalogMatch&&r?.backend?.mode!=='private-api'){try{r=await window.DCCatalogMatch(r)}catch(e){console.warn('Catalog match failed',e)}}renderBase(r);document.dispatchEvent(new CustomEvent('dc:design',{detail:r}));return r;}

async function run(){const b=$('run');b.disabled=true;b.textContent='…';try{const res=await fetch('/api/design',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});const data=await res.json();await render(data);}catch(e){await render({status:'REVIEW',error:e.message});}finally{b.disabled=false;b.textContent=I18N[lang].run;}}
$('run').addEventListener('click',run);run();
