(function(){
'use strict';const T=window.__LS3D_TEST__;if(!T)return;const $=x=>document.getElementById(x);
const defs={aidc:[20,36,80,'mixed',35,20,45,'N+1',1.36,24,900,1800,1600,12],'server-room':[3,8,0,'air',100,0,0,'N',1.55,24,35,0,30,15],onprem:[12,15,15,'rear',25,75,0,'N+1',1.48,24,220,600,500,10]};
const c=window.LS3D_CONFIG={rackCount:0,rackPowerKw:0,gpuRatio:0,cooling:'air',air:0,rear:0,dlc:0,redundancy:'N+1',pue:1.36,pueMin:1.1,pueMax:2,outdoorC:24,coolingKw:0,generatorKw:0,upsKw:0,batteryMin:12,mode:'pluggable',plugW:8,cpoW:4,plugKw:18,cpoKw:14,portCount:128,cpoPue:.08,density:1.35,selected:'tor-spine-a',broken:null,reroute:false,edited:false,quality:'medium'};
function preset(id){let a=defs[id]||defs.aidc;[c.rackCount,c.rackPowerKw,c.gpuRatio,c.cooling,c.air,c.rear,c.dlc,c.redundancy,c.pue,c.outdoorC,c.coolingKw,c.generatorKw,c.upsKw,c.batteryMin]=a;c.edited=false}
preset(T.facilityMode);
const LOSS={smfDbKm:.22,mmfDbKm:3,connectorDb:.25,spliceDb:.10,cpoCouplingDb:.15};
const nodes=[['server','GPU NIC',[3,0],'gpu-0-0'],['torA','ToR / Leaf A',[15,0],'tor-a'],['torB','ToR / Leaf B',[22,5],'tor-b'],['spA','Spine A',[8,18],'spine-a'],['spB','Spine B',[22,18],'spine-b'],['core','Core',[15,28],'core'],['odf','ODF / MMR',[-5,28],'odf'],['isp','Campus / ISP',[-22,28],'carrier']].map(x=>({id:x[0],name:x[1],pos:x[2],asset:x[3]}));
const links=[
['server-tor','server','torA','DAC/AEC','MMF',0,'QSFP electrical','400G',5,2,0,0,'A'],
['server-tor-b','server','torB','DAC/AEC','MMF',0,'QSFP electrical','400G',7,2,0,0,'B'],
['tor-spine-a','torA','spA','SMF trunk','SMF',24,'MPO-16','800G assumed',34,4,2,4,'A'],
['tor-spine-a-b','torA','spB','SMF redundant','SMF',24,'MPO-16','800G assumed',42,4,2,4,'B'],
['tor-spine-b','torB','spB','SMF trunk','SMF',24,'MPO-16','800G assumed',36,4,2,4,'B'],
['tor-spine-b-a','torB','spA','SMF redundant','SMF',24,'MPO-16','800G assumed',44,4,2,4,'A'],
['spine-core-a','spA','core','SMF trunk','SMF',24,'MPO-16','800G assumed',48,4,2,4,'A'],
['spine-core-b','spB','core','SMF redundant','SMF',24,'MPO-16','800G assumed',54,4,2,4,'B'],
['core-odf','core','odf','SMF patch','SMF',48,'LC duplex','400/800G assumed',62,4,2,4.5,'A'],
['odf-isp','odf','isp','Carrier cross-connect','SMF',96,'MPO/LC','400G assumed',85,4,4,5,'A'],
['campus-dci','isp','core','Campus DCI SMF','SMF',24,'LC duplex','400G assumed',950,4,12,6,'B']
].map(x=>({id:x[0],from:x[1],to:x[2],type:x[3],media:x[4],cores:x[5],connector:x[6],speed:x[7],length:x[8],conn:x[9],splice:x[10],budget:x[11],route:x[12],down:false}));
const N=id=>nodes.find(x=>x.id===id),L=id=>links.find(x=>x.id===id),A=id=>T.assets.find(x=>x.id===id),esc=x=>String(x).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function loss(l){let alpha=l.media==='MMF'?LOSS.mmfDbKm:LOSS.smfDbKm,val=l.length/1000*alpha+l.conn*LOSS.connectorDb+l.splice*LOSS.spliceDb+(c.mode==='cpo'&&l.media==='SMF'?LOSS.cpoCouplingDb:0);return [val,l.budget?l.budget-val:null,alpha]}
function event(sev,msg,l){if(T.addEventLog)T.addEventLog(sev,msg,A(N(l?.from)?.asset)||A('odf')||T.selected,'fiber')}
function flow(){T.flowPaths.fiber.splice(0,T.flowPaths.fiber.length,...links.filter(x=>!x.down).map(x=>[N(x.from).pos,N(x.to).pos]));let e=$('optState');if(e)e.textContent=c.broken?(c.reroute?'우회 경로 · 지연 +18 µs · 가용 대역폭 65%':'연결 끊김 · 대체 경로 없음'):'정상 경로 · 교육용 가정값'}
function calc(){let load=c.rackCount*c.rackPowerKw,op=(c.mode==='cpo'?c.cpoW:c.plugW)*c.portCount/1000+(c.mode==='cpo'?c.cpoKw:c.plugKw),pue=Math.max(c.pueMin,Math.min(c.pueMax,c.pue+Math.max(0,c.outdoorC-20)*.012+(c.cooling==='dlc'?-.045:c.cooling==='rear'?-.02:c.cooling==='mixed'?.005:.035)-(c.mode==='cpo'?c.cpoPue:0))),fac=(load+op)*pue,temp=22+Math.max(0,load/Math.max(1,c.coolingKw)*100-70)*.065;let elapsed=T.scenarioElapsed?T.scenarioElapsed():0,sc=T.scenario;if(sc==='gpu-surge'){let r=Math.min(1,elapsed/180);load*=1+.55*r;pue=Math.min(c.pueMax,pue+.1*r);fac=(load+op)*pue}if(sc==='dlc-leak'&&elapsed>45)load*=.75;if(sc==='rack-hotspot'&&elapsed>100)load*=.85;if(sc==='fire')temp+=13;if(sc==='dlc-leak')temp+=9;if(sc==='rack-hotspot')temp+=Math.min(17,elapsed/10);if(sc==='cooling')temp+=Math.min(16,elapsed/70);if(sc==='ups-battery'&&elapsed>=c.batteryMin*60)load*=.2;fac=(load+op)*pue;let avail=c.broken?(c.reroute?99.2:0):sc==='network'?85:sc==='power'?96:sc==='fire'?70:sc==='dlc-leak'?91:sc==='rack-hotspot'?92:sc==='ups-battery'&&elapsed>=c.batteryMin*60?0:100;let m={load:load+op,facility:fac,pue,temperature:temp,availability:avail,latency:c.broken?18:sc==='fiber-cut'?18:0,bandwidth:c.broken?65:sc==='fiber-cut'?65:100};if(c.edited){$('kpiLoad').innerHTML=m.load.toFixed(0)+'<small>kW</small>';$('kpiFacility').innerHTML=fac.toFixed(0)+'<small>kW</small>';$('kpiFacilityMeta').textContent='가상 PUE '+pue.toFixed(2);$('kpiAvailability').innerHTML=m.availability.toFixed(1)+'<small>%</small>';$('kpiTemp').innerHTML=temp.toFixed(1)+'<small>°C</small>'}if($('thermalOut'))$('thermalOut').textContent='공급/회수 18 / 23°C · ΔT 5°C · 유량 '+(load/(4.186*5)*60).toFixed(0)+' L/min · 냉각 부하율 '+(load/Math.max(1,c.coolingKw)*100).toFixed(1)+'% · 랙 입구 22–24°C '+Math.round(c.rackCount*.45)+'대, 24–27°C '+Math.round(c.rackCount*.4)+'대, 나머지 >27°C (가정)';if($('warn'))$('warn').textContent=(c.pueMin>c.pueMax?'경고: 목표 PUE 하한은 상한 이하여야 합니다. ':c.air+c.rear+c.dlc!==100?'경고: 냉각 비율 합계를 100%로 맞춰주세요. ':load>c.coolingKw?'경고: 랙 전력이 냉각 용량을 초과합니다. ':c.generatorKw<load?'주의: 발전기 가정 용량이 IT 부하 미만입니다. ':c.upsKw<load?'주의: UPS 가정 용량이 IT 부하 미만입니다. ':'')+'계산값은 교육·설계 검토용 가정입니다.';if($('cpoOut'))$('cpoOut').textContent='플러거블 '+(c.portCount*c.plugW/1000+c.plugKw).toFixed(1)+' kW · CPO '+(c.portCount*c.cpoW/1000+c.cpoKw).toFixed(1)+' kW · 전력비중 '+(op/fac*100).toFixed(2)+'% · 포트밀도 '+(c.mode==='cpo'?c.density:1).toFixed(2)+'× · 냉각 PUE 효과 '+(c.mode==='cpo'?-c.cpoPue:0).toFixed(2)+' (가정)';return m}
function optics(){let svg=$('optSvg'),pos={server:[35,75],torA:[140,45],torB:[140,105],spA:[260,45],spB:[260,110],core:[380,78],odf:[500,78],isp:[615,78]};svg.innerHTML=links.map(l=>{let a=pos[l.from],b=pos[l.to];return '<path class="ol '+(l.route==='B'?'alt ':'')+(l.down?'bad':'')+'" data-link="'+l.id+'" d="M'+a[0]+' '+a[1]+' Q'+((a[0]+b[0])/2)+' '+((a[1]+b[1])/2-12)+' '+b[0]+' '+b[1]+'"/>'}).join('')+nodes.map(n=>'<g><rect x="'+(pos[n.id][0]-33)+'" y="'+(pos[n.id][1]-10)+'" width="66" height="20" rx="5"/><text x="'+pos[n.id][0]+'" y="'+(pos[n.id][1]+3)+'" text-anchor="middle">'+esc(n.name)+'</text></g>').join('');svg.querySelectorAll('[data-link]').forEach(x=>x.onclick=()=>{c.selected=x.dataset.link;optics()});$('optList').innerHTML=links.map(l=>'<button data-sel="'+l.id+'">'+esc(N(l.from).name)+' → '+esc(N(l.to).name)+' · '+l.length+'m · '+(l.down?'단선':'정상')+'</button>').join('');$('optList').querySelectorAll('[data-sel]').forEach(x=>x.onclick=()=>{c.selected=x.dataset.sel;optics()});let l=L(c.selected)||links[0];c.selected=l.id;let b=loss(l);$('optDetail').innerHTML='<div class="twin-readout">거리 '+l.length+'m · 매체/코어 '+l.media+'/'+(l.cores||'전기')+' · '+l.connector+' · '+l.speed+' · 손실 '+b[0].toFixed(2)+' dB · 마진 '+(b[1]==null?'전기 링크':b[1].toFixed(2)+' dB')+'</div><label>거리 m <input id="ln" type="number" value="'+l.length+'"></label><label>커넥터 수 <input id="cn" type="number" value="'+l.conn+'"></label><label>스플라이스 수 <input id="sp" type="number" value="'+l.splice+'"></label><small>손실 = km×'+b[2]+' dB/km + 커넥터×0.25 dB + 스플라이스×0.10 dB. 속도/수신 예산은 400G·800G 가정이며 실제 규격이 아닙니다.</small><button id="cut">'+(l.down?'복구':'선택 링크 단선')+'</button>';for(const [id,key] of [['ln','length'],['cn','conn'],['sp','splice']])$(''+id).onchange=e=>{l[key]=+e.target.value||0;optics()};$('cut').onclick=()=>{if(l.down){l.down=false;c.broken=null;c.reroute=false;event('INFO','광 링크 복구',l)}else{l.down=true;c.broken=l.id;const backupId={'server-tor':'server-tor-b','server-tor-b':'server-tor','tor-spine-a':'tor-spine-a-b','tor-spine-a-b':'tor-spine-a','tor-spine-b':'tor-spine-b-a','tor-spine-b-a':'tor-spine-b','spine-core-a':'spine-core-b','spine-core-b':'spine-core-a'}[l.id],backup=backupId&&L(backupId);c.reroute=c.redundancy!=='N'&&!!backup&&!backup.down;c.brokenAt=T.simTime;event('CRITICAL','광케이블 단선: '+l.id,l);if(c.reroute)event('WARN','대체 Spine 경로로 우회',l);T.scenarioApply('fiber-cut')}flow();optics();calc()};flow()}
function saveJson(){let o={schemaVersion:'lsdc-twin-bom/1.0',units:{power:'kW',length:'m',temperature:'degC',loss:'dB'},assumptionNotice:'교육·설계 검토용 가정값 · 공식 제품 사양 아님',facility:{profile:T.facilityMode,rackCount:c.rackCount,rackPowerKw:c.rackPowerKw,gpuServerRatio:c.gpuRatio/100,createdAt:new Date().toISOString(),assumptionNotice:'교육·설계 검토용 가정값 · 실제 제품 사양 아님',units:{power:'kW',length:'m',temperature:'degC',flow:'L/min',loss:'dB',time:'min'},cooling:{mode:c.cooling,airPct:c.air,rearDoorPct:c.rear,dlcPct:c.dlc,capacityKw:c.coolingKw},redundancy:c.redundancy,targetPue:c.pue,pueRange:{min:c.pueMin,max:c.pueMax},outdoorC:c.outdoorC,generatorKw:c.generatorKw,upsKw:c.upsKw,batteryMinutes:c.batteryMin},optical:{topology:{nodes:nodes.map(n=>({id:n.id,name:n.name,layer:n.id==='server'?'Rack':n.id.startsWith('tor')?'Leaf':n.id.startsWith('sp')?'Spine':n.id==='core'?'Core':n.id==='odf'?'MMR':'External',x:n.pos[0],z:n.pos[1]})),links:links.map(l=>({id:l.id,from:l.from,to:l.to,type:l.type,fiber:l.media,cores:l.cores,connector:l.connector,speed:l.speed,lengthM:l.length,connectors:l.conn,splices:l.splice,budgetDb:l.budget,down:l.down}))},cpoMode:c.mode,assumptions:{pluggablePortW:c.plugW,cpoPortW:c.cpoW,pluggableSwitchKw:c.plugKw,cpoSwitchKw:c.cpoKw,cpoCoolingPue:c.cpoPue,portCount:c.portCount,loss:{smfDbKm1550:.22,mmfDbKm850:3,connectorDb:.25,spliceDb:.10,cpoCouplingDb:.15}}}};let a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(o,null,2)],{type:'application/json'}));a.href=u;a.download='lsdc-twin-config.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function layout(){let profile=T.facilityProfiles[T.facilityMode],pref=T.facilityMode==='server-room'?'company-rack-':T.facilityMode==='onprem'?'onprem-rack-':'gpu-',racks=T.assets.filter(x=>T.facilityMode==='aidc'?(/^gpu-\d-\d$/.test(x.id)||x.id.startsWith('gpu-extra-')):x.id.startsWith(pref)),n=Math.min(20,Math.max(1,c.rackCount)),proto=racks[0]||T.assets.find(x=>x.type==='GPU server rack');for(let i=0;i<n;i++){let x=racks[i];if(!x&&proto){x={...proto,id:pref+'extra-'+String(i+1).padStart(2,'0'),name:'대표 랙 '+(i+1),type:'GPU server rack',down:false};T.assets.push(x);T.assetMap.set(x.id,x);racks.push(x);if(profile.ids&&!profile.ids.includes(x.id))profile.ids.push(x.id)}if(x){x.hidden=false;x.zone='hall';x.x=1+(i%5)*3.5;x.z=-2+Math.floor(i/5)*8;x.power=c.rackPowerKw+' kW/랙 · 가정'}}for(let i=n;i<racks.length;i++)racks[i].hidden=true}
function form(){let vals=[['rackCount','랙 수',1,500],['rackPowerKw','랙당 kW',1,200],['gpuRatio','GPU 서버 비율 %',0,100],['air','공랭 %',0,100],['rear','후면열교환기 %',0,100],['dlc','DLC %',0,100],['pue','목표 PUE',1,3],['pueMin','PUE 하한',1,3],['pueMax','PUE 상한',1,3],['outdoorC','외기 °C',-20,50],['coolingKw','냉각 용량 kW',1,1000000],['generatorKw','발전기 kW',0,1000000],['upsKw','UPS kW',0,1000000],['batteryMin','UPS 백업 분',1,180],['portCount','광 포트 수',1,100000],['plugW','플러거블 포트 W',.1,100],['cpoW','CPO 포트 W',.1,100],['plugKw','플러거블 스위치 kW',0,100000],['cpoKw','CPO 스위치 kW',0,100000],['cpoPue','CPO 냉각 영향 PUE',0,1],['density','CPO 포트 밀도 배율',.1,10]];$('cfgFields').innerHTML=vals.map(x=>'<label>'+x[1]+'<input data-k="'+x[0]+'" type="number" min="'+x[2]+'" max="'+x[3]+'" value="'+c[x[0]]+'"></label>').join()+'<label>냉각 방식<select data-k="cooling"><option>air</option><option>rear</option><option>dlc</option><option>mixed</option></select></label><label>이중화<select data-k="redundancy"><option>N</option><option>N+1</option><option>2N</option></select></label><label>CPO 비교<select data-k="mode"><option value="pluggable">플러거블 광모듈</option><option value="cpo">CPO</option></select></label><label>렌더 품질<select data-k="quality"><option value="low">품질 낮음</option><option value="medium">품질 보통</option><option value="high">품질 높음</option></select></label>';$('cfgFields').querySelectorAll('[data-k]').forEach(e=>{e.value=c[e.dataset.k];e.oninput=()=>{let v=e.type==='number'?+e.value:e.value;if(e.type==='number'&&(v<+e.min||v>+e.max))return;c[e.dataset.k]=v;c.edited=true;if(e.dataset.k==='redundancy'){$('redundancySelect').value=v;$('redundancySelect').dispatchEvent(new Event('change',{bubbles:true}));T.redundancy=v}if(e.dataset.k==='batteryMin')battery();if(e.dataset.k==='mode')optics();if(e.dataset.k==='rackCount'||e.dataset.k==='rackPowerKw')layout();calc()}});$('redundancySelect').value=c.redundancy;$('redundancySelect').dispatchEvent(new Event('change',{bubbles:true}))}
function build(){let loading=document.createElement('div');loading.textContent='3D 데이터센터 씬 초기화 중 · 가정값 모델 로딩';loading.style='position:fixed;z-index:100;inset:0;display:grid;place-items:center;background:#071523;color:#d8f4ff;font:700 12px system-ui';document.body.append(loading);setTimeout(()=>loading.remove(),650);let st=document.createElement('style');st.textContent='.twin-modal{display:none;position:fixed;z-index:80;inset:0;background:#020b14d9;justify-content:flex-end}.twin-modal.open{display:flex}.twin-panel{width:min(520px,100vw);height:100dvh;overflow:auto;background:#0c1d2d;padding:16px;color:#e5f7ff;border-left:1px solid #345}.twin-panel h2{font-size:17px}.twin-panel p,.twin-panel small{font-size:10px;line-height:1.6;color:#9fb8c8}.twin-panel label{display:block;font-size:10px;color:#adc3d0}.twin-panel input,.twin-panel select{width:100%;padding:7px;margin:4px 0 8px;background:#081928;color:white;border:1px solid #345;border-radius:6px}.top-actions>span{display:flex;gap:4px}.top-actions>span button{white-space:nowrap}.twin-panel button{background:#153d50;color:#e6ffff;border:1px solid #398397;border-radius:7px;padding:8px;margin:3px;font-size:10px}.twin-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.twin-readout{padding:8px;background:#132c40;border-radius:7px;font-size:10px}.optical-svg{width:100%;background:#081928;border:1px solid #345}.optical-svg path{fill:none;stroke:#55ddc4;stroke-width:4;cursor:pointer}.optical-svg path.alt{stroke:#7aa8ff;stroke-dasharray:5 4}.optical-svg path.bad{stroke:#ff7086}.optical-svg rect{fill:#173950;stroke:#7aa}.optical-svg text{fill:white;font:9px system-ui}#optList button{display:block;width:100%;text-align:left}@media(max-width:420px){.top-actions>span button{font-size:8px;padding:5px 6px}.top-actions{gap:3px}}@media(max-width:790px){.twin-modal{align-items:flex-end}.twin-panel{height:90dvh;width:100%;border-radius:15px 15px 0 0}}';document.head.append(st);
let bar=document.querySelector('.top-actions'),b=document.createElement('span');b.innerHTML='<button id="cfgOpen">⚙ 설정</button><button id="optOpen">◎ 광</button><button id="guideOpen">? 안내</button>';bar.prepend(b);
document.body.insertAdjacentHTML('beforeend','<div class="twin-modal" id="twinSettings"><section class="twin-panel"><h2>AI 데이터센터 가정값</h2><button data-close>닫기</button><p>교육·설계 검토용 값 · 변경 즉시 계산 반영</p><div><button data-p="server-room">소규모 서버실</button><button data-p="onprem">엔터프라이즈</button><button data-p="aidc">AI 학습 캠퍼스</button></div><div id="cfgFields" class="twin-grid"></div><p id="warn"></p><p id="thermalOut"></p><b>CPO / 플러거블 비교</b><p id="cpoOut"></p><p>시설전력=(IT+광 네트워크)×PUE. 냉각 유량=열부하/(4.186×ΔT)×60. 외기 20°C 초과분 1°C당 PUE +0.012 가정.</p><button id="jsonOut">JSON 내보내기</button><button id="jsonIn">JSON 불러오기</button><input id="jsonFile" type="file" accept=".json" hidden><button id="bomOut">BOM 툴로 전달 ↗</button><button id="reset">초기값 복원</button></section></div><div class="twin-modal" id="optModal"><section class="twin-panel"><h2>광 네트워크 토폴로지</h2><button data-close>닫기</button><p>Rack NIC → ToR/Leaf → Spine → Core → ODF/MMR → ISP · 가정값</p><div id="optState"></div><svg id="optSvg" class="optical-svg" viewBox="0 0 650 145"></svg><div id="optList"></div><div id="optDetail"></div></section></div><div class="twin-modal" id="guide"><section class="twin-panel"><h2>빠른 안내 · 5단계</h2><p>1 구역 선택 → 2 설비 클릭 → 3 전력·냉각·광 흐름 토글 → 4 장애 시나리오와 링크 직접 단선 → 5 작업자 시점 보기.</p><p>PC: 드래그 회전·휠 줌·우클릭 이동. 모바일: 한 손가락 회전·두 손가락 이동/줌. 키보드 1–7 구역 이동, ESC 닫기.</p><button data-close>닫기</button></section></div>');
$('cfgOpen').onclick=()=>{form();$('twinSettings').classList.add('open')};$('optOpen').onclick=()=>{$('optModal').classList.add('open');optics()};$('guideOpen').onclick=()=>$('guide').classList.add('open');document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>x.closest('.twin-modal').classList.remove('open'));
document.querySelectorAll('[data-p]').forEach(x=>x.onclick=()=>{T.applyFacilityMode(x.dataset.p);preset(x.dataset.p);layout();form();calc()});
$('jsonOut').onclick=saveJson;$('jsonIn').onclick=()=>$('jsonFile').click();$('jsonFile').onchange=e=>{let f=e.target.files[0];if(f){let r=new FileReader();r.onload=()=>{try{let o=JSON.parse(r.result);if(o.schemaVersion!=='lsdc-twin-bom/1.0')throw Error('schema mismatch');Object.assign(c,o.facility,{cooling:o.facility.cooling.mode,air:o.facility.cooling.airPct,rear:o.facility.cooling.rearDoorPct,dlc:o.facility.cooling.dlcPct,gpuRatio:o.facility.gpuServerRatio*100,pueMin:o.facility.pueRange?.min||c.pueMin,pueMax:o.facility.pueRange?.max||c.pueMax,edited:true});if(o.optical){c.mode=o.optical.cpoMode||c.mode;Object.assign(c,{plugW:o.optical.assumptions.pluggablePortW||c.plugW,cpoW:o.optical.assumptions.cpoPortW||c.cpoW,plugKw:o.optical.assumptions.pluggableSwitchKw||c.plugKw,cpoKw:o.optical.assumptions.cpoSwitchKw||c.cpoKw,portCount:o.optical.assumptions.portCount||c.portCount});(o.optical.topology?.links||[]).forEach(q=>{let l=L(q.id);if(l){l.length=q.lengthM??l.length;l.conn=q.connectors??l.conn;l.splice=q.splices??l.splice;l.down=!!q.down}})}form();calc();optics()}catch(z){alert('JSON 오류: '+z.message)}};r.readAsText(f)}};
$('bomOut').onclick=()=>{saveJson();window.open('./index.html','_blank','noopener')};$('reset').onclick=()=>{preset(T.facilityMode);form();calc()};$('redundancySelect').addEventListener('change',e=>{c.redundancy=e.target.value;flow()});
$('facilityModeSelect').onchange=e=>{T.applyFacilityMode(e.target.value);preset(e.target.value);form();calc()};
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.twin-modal').forEach(x=>x.classList.remove('open'));if(/^[1-7]$/.test(e.key)&&!['INPUT','SELECT'].includes(document.activeElement.tagName)){let z=T.visibleZones()[+e.key-1];if(z)T.setZone(z.id)}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)T.simRunning=false});
const oldScenario=T.scenarioApply;T.scenarioApply=function(id){oldScenario(id);if(id==='normal'&&c.broken){let l=L(c.broken);if(l)l.down=false;c.broken=null;c.reroute=false;flow();optics()}};
T.metrics=(function(old){return function(){let m=old();if(c.edited||c.broken){let x=calc();x.availability=Math.min(m.availability,x.availability);Object.assign(m,x)}return m}})(T.metrics);
let up=T.scenarioDefs.find(x=>x.id==='ups-battery');const battery=()=>{if(up){let t=Math.max(60,c.batteryMin*60);up.timeline[2][0]=t/2;up.timeline[3][0]=t;up.timeline[4][0]=t+120}};
battery();
let tempAlarm=false,capacityAlarm=false;setInterval(()=>{let live=calc();if(live.temperature>27&&!tempAlarm){event('WARN','랙 입구 온도 가정값 27°C 초과',L(c.selected));tempAlarm=true}if(live.temperature<=27)tempAlarm=false;if(c.rackCount*c.rackPowerKw>c.coolingKw&&!capacityAlarm){event('CRITICAL','IT 부하가 냉각 용량 가정을 초과',L(c.selected));capacityAlarm=true}if(c.rackCount*c.rackPowerKw<=c.coolingKw)capacityAlarm=false;if(c.broken&&T.simTime-c.brokenAt>180){let l=L(c.broken);l.down=false;event('INFO','광 링크 복구',l);c.broken=null;c.reroute=false;flow();optics()}},400);

/* Incident response fleet: four field engineers ride service vans to the affected zone.
   Campus roads and travel speed are illustrative training assumptions. */
let responseDispatch=null;
const originalPose=T.npcPose;
const roadRoutes={
 utility:[[-3,29],[-3,-35],[-47,-35],[-47,-39]],
 cooling:[[35,29],[35,-35],[47,-35],[47,-39]],
 gray:[[-3,29],[-25,29],[-25,26]],
 hall:[[-3,29],[15,29],[15,27]],
 network:[[35,29],[44,29],[44,28]],
 ops:[[-3,29],[-43,29],[-43,27]],
 campus:[[26,29],[26,47]]
};
function incidentStage(){const d=T.scenarioDefs.find(x=>x.id===T.scenario);if(!d)return null;const t=T.scenarioElapsed();let st=d.timeline[0];for(const row of d.timeline)if(t>=row[0])st=row;return {def:d,stage:st,elapsed:t,index:d.timeline.indexOf(st)}}
function incidentAsset(){
 const q=incidentStage();if(!q)return null;
 const id=q.stage[4],visible=T.visibleAssets(),a=(id&&T.assetMap.get(id)&&visible.some(x=>x.id===id)&&T.assetMap.get(id))||q.def.assets.map(x=>T.assetMap.get(x)).find(x=>x&&visible.some(y=>y.id===x.id));
 return a||T.selected;
}
function distance2(a,b){return Math.hypot(b[0]-a[0],b[1]-a[1])}
function routeLen(route){return route.slice(1).reduce((n,p,i)=>n+distance2(route[i],p),0)}
function pointOnRoute(route,d){for(let i=1;i<route.length;i++){const a=route[i-1],b=route[i],len=distance2(a,b);if(d<=len){const t=len?d/len:1;return {x:a[0]+(b[0]-a[0])*t,z:a[1]+(b[1]-a[1])*t,heading:Math.atan2(b[1]-a[1],b[0]-a[0])}}d-=len}const b=route[route.length-1],a=route[route.length-2]||b;return {x:b[0],z:b[1],heading:Math.atan2(b[1]-a[1],b[0]-a[0])}}
function responseTarget(a,index){
 const z=T.Z.find(x=>x.id===a.zone),dx=a.x-z.pos[0],dz=a.z-z.pos[1],n=Math.hypot(dx,dz)||1;
 const side=Math.max(a.w,a.d)*.72+2;
 return [a.x-dx/n*side+(index-1.5)*.72,a.z-dz/n*side];
}
function makeResponseRoute(n,index,a){
 const p=originalPose(n),start=[p.x,p.z],roads=roadRoutes[a.zone]||roadRoutes.campus,park=responseTarget(a,index);
 return [start,...roads,park];
}
function startResponse(){
 responseDispatch=null;if(T.scenario==='normal')return;if(T.scenario==='fire'){const safeTarget=incidentAsset();responseDispatch={scenario:'fire',start:T.simTime,asset:safeTarget,people:[]};if(safeTarget){T.setZone(safeTarget.zone);T.pickAsset(safeTarget,true);T.cameraDesired.distance=55;T.cameraDesired.target=[safeTarget.x,2,safeTarget.z]}return;}
 const a=incidentAsset();if(!a)return;
 const staff=T.npcs.filter(n=>n.role!=='guard'&&T.facilityProfiles[T.facilityMode].staff.includes(n.id)).slice(0,4);
 const people=staff.map((n,i)=>{const route=makeResponseRoute(n,i,a),drive=routeLen(route)/7.5;return {n,index:i,route,drive,arrive:drive+2.5,asset:a,park:route[route.length-1],inspect:[a.x+(i-1.5)*.8,a.z+a.d*.65]}});
 responseDispatch={scenario:T.scenario,start:T.simTime,asset:a,people};
 T.setZone(a.zone);T.pickAsset(a,true);T.cameraDesired.distance=55;T.cameraDesired.target=[a.x,2,a.z];
 T.addEventLog('INFO','현장 출동 차량 4대 배차 · 엔지니어 이동 시작',a,'response');
}
function responsePose(n){
 if(!responseDispatch||responseDispatch.scenario!==T.scenario)return originalPose(n);
 const p=responseDispatch.people.find(x=>x.n.id===n.id);if(!p)return originalPose(n);
 const t=Math.max(0,T.simTime-responseDispatch.start);
 if(t<p.drive){const v=pointOnRoute(p.route,t*7.5);return {...v,action:'ride'}}
 if(t<p.arrive){const v=pointOnRoute(p.route,routeLen(p.route));return {...v,action:'ride'}}
 const walk=Math.min(1,(t-p.arrive)/2.8),start=p.park,end=p.inspect;
 return {x:start[0]+(end[0]-start[0])*walk,z:start[1]+(end[1]-start[1])*walk,heading:Math.atan2(end[1]-start[1],end[0]-start[0]),action:walk<1?'walk':'inspect'}
}
T.npcPose=responsePose;
window.LS3D_RESPONSE_ACTIVE=function(id){return T.scenario==='fire'&&!!responseDispatch&&responseDispatch.scenario==='fire'&&T.facilityProfiles[T.facilityMode].staff.includes(id)||!!responseDispatch&&responseDispatch.people.some(x=>x.n.id===id)};
function drawResponse(ctx){
 const q=incidentStage(),active=T.scenario!=='normal'&&q&&!q.stage[5]?.includes('recovery');
 if(responseDispatch&&responseDispatch.scenario===T.scenario){
  responseDispatch.people.forEach(function(p){const t=Math.max(0,T.simTime-responseDispatch.start),dist=Math.min(routeLen(p.route),t*7.5),v=pointOnRoute(p.route,dist),rot=v.heading;
   ctx.box(v.x,.04,v.z,2.35,.78,1.08,'#d8e1e7',rot);ctx.box(v.x,.82,v.z-.03,1.12,.55,.9,'#7ba2b5',rot);ctx.box(v.x+.62,.84,v.z-.03,.38,.12,.66,'#f4c86c',rot);
   ctx.box(v.x-.84,.10,v.z-.60,.38,.38,.17,'#172532',rot);ctx.box(v.x-.84,.10,v.z+.60,.38,.38,.17,'#172532',rot);ctx.box(v.x+.84,.10,v.z-.60,.38,.38,.17,'#172532',rot);ctx.box(v.x+.84,.10,v.z+.60,.38,.38,.17,'#172532',rot);
   ctx.box(v.x,.04,v.z,2.0,.03,1.18,'#f8cc67',rot,'glass');
   if(t<p.arrive+16&&T.scenarioElapsed()>Math.max(45,p.drive)){ctx.box(v.x,.025,v.z,2.6,.025,1.4,[.2,.85,.72,.62],0,'glass')}
  });
 }
 if(!active||!q)return;
 const a=incidentAsset();if(!a)return;const t=q.elapsed,phase=q.stage[5],smokeColor=[.69,.75,.81,.74];
 if(T.scenario==='dlc-leak')ctx.box(a.x,.055,a.z,a.w*1.5,.055,a.d*1.5,[.18,.72,.93,.55],0,'glass');
 if(T.scenario==='rack-hotspot')ctx.ring(a.x,.18,a.z,Math.max(a.w,a.d)*.88,t%1<.5?'#fb806f':'#ffc17a',34);
 if(T.scenario==='fiber-cut'){for(let i=0;i<5;i++){const x=a.x+Math.sin(t*.22+i*2)*.9,z=a.z+Math.cos(t*.19+i*2)*.8;ctx.box(x,1+i%2*.65,z,.16,.65,.16,'#ffd476',t*.15+i)}}
 if(T.scenario==='fire'||T.scenario==='power'||T.scenario==='cooling'||T.scenario==='dlc-leak'||T.scenario==='rack-hotspot'||T.scenario==='ups-battery'){
  const sx=a.x+a.w*.18,sz=a.z-a.d*.18;
  for(let i=0;i<7;i++){const rise=(t*.62+i*1.55)%10,x=sx+Math.sin(t*.08+i*2)*(.45+rise*.15),y=a.h+.4+rise*.44,z=sz+Math.cos(t*.07+i)*.42;const size=1.15+rise*.20;ctx.box(x,y,z,size,size*.78,size,smokeColor,0,'glass')} if(T.scenario==='fire'){const blink=t%1<.5;ctx.box(a.x,.12,a.z,a.w+3,.1,a.d+3,blink?'#ed5965':'#923847',0,'glass');ctx.box(a.x,.3,a.z,.9,2.2,.9,blink?'#ff704f':'#f5bb50',0,'glass')}
 }
 if(T.scenario==='fire'&&q.index>=4&&q.index<6){const pulse=t%1<.5;ctx.box(a.x,.1,a.z,a.w+2,.08,a.d+2,pulse?'#d7e4ec':'#83cbd1',0,'glass');for(let i=0;i<5;i++)ctx.cylinder(a.x-1.8+i*.9,.2+(t%3)*.55,a.z,.5,1.1,[.78,.86,.9,.2],12)}
 if(phase==='recovery')responseDispatch=null;
}
window.LS3D_RESPONSE_VISUALS=window.LS3D_RESPONSE_VISUALS||[];window.LS3D_RESPONSE_VISUALS.push(drawResponse);
const baseResponseScenario=scenarioApply;
scenarioApply=function(id){baseResponseScenario(id);if(id==='normal'){responseDispatch=null}else startResponse()};
T.scenarioApply=scenarioApply;
if(!T.gl){let a=document.createElement('a');a.href='./LS_Datacenter_Campus.html';a.textContent='WebGL 미지원 · 2D Gold Pixel Tour';a.style='position:fixed;bottom:8px;z-index:99;background:#432;color:white;padding:10px';document.body.append(a)}
layout();try{if(!sessionStorage.getItem('twin-guide')){$('guide').classList.add('open');sessionStorage.setItem('twin-guide','1')}}catch(e){}
layout();form();flow();optics();calc()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();