(() => {
  'use strict';
  const $=id=>document.getElementById(id),M=window.DCPlanning;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const number=n=>Number(n).toLocaleString('ko-KR',{maximumFractionDigits:2});
  const engineDesign=DCBOMEngine.design.bind(DCBOMEngine);
  DCBOMEngine.design=input=>{
    const i={...input},preset=M.presets[i.systemId],selection=i.systemId;
    try{if(i.regionPduEnabled)i.pduRatedKw=M.regionalCapacity(i);}catch(e){return {usable:false,status:'INVALID',error:e.message,input};}
    if(preset){i.systemId='custom';i.customName=preset.name;}
    const r=engineDesign(i);
    if(r.input)Object.assign(r.input,{acceleratorSelection:selection,regionId:input.regionId,siteVoltage:input.siteVoltage,siteFrequency:input.siteFrequency,sitePhases:input.sitePhases,siteCurrentA:input.siteCurrentA,regionPduEnabled:input.regionPduEnabled,regionalFramework:input.regionalFramework,quoteCurrency:input.quoteCurrency});
    if(r.usable&&preset&&r.input.scenario!=='colo'){r.systemProfile.gpu=selection;r.systemProfile.evidence='OEM 미선정 · 전력/RU/외부 포트 사용자 가정';r.systemProfile.source=preset.source;r.products[0].vendor=preset.vendor;r.products[0].evidence='계획 가정';r.products[0].source=preset.source;r.warnings.push(preset.note+' 외부 패브릭은 범용 Ethernet 계획안입니다.');}
    if(r.usable){r.planningTotals=M.totals(r);r.validation=M.checks(r);r.region={name:M.regions[input.regionId]?.name||'현장 미선택',voltage:input.siteVoltage,hz:input.siteFrequency,phases:input.sitePhases,framework:input.regionalFramework,pduRatedKw:r.input.pduRatedKw,capacityApplied:!!input.regionPduEnabled,status:'규격 적합성·분기 보호·서버 입력전압·인증서 확인 필요'};}
    return r;
  };
  const engineering=window.getEngineeringInputs;
  window.getEngineeringInputs=()=>{const x=engineering();for(const id of ['regionId','siteVoltage','siteFrequency','sitePhases','siteCurrentA','regionalFramework','quoteCurrency','customName','customGpus','customRU','customKw','customLinks','customSpeed','customLogicalPerCage','customCords'])if($(id))x[id]=$(id).type==='number'?Number($(id).value):$(id).value;x.regionPduEnabled=$('regionPduEnabled')?.checked||false;return x;};
  const regions=document.createElement('section');regions.className='inputGroup';regions.id='region-inputs';regions.innerHTML='<h3>지역 전원·조달 규격</h3><div class="fields sub"><label><span>지역 전원 예시</span><select id="regionId"><option value="custom">현장 지정 · 기본 400 V / 50 Hz</option>'+Object.entries(M.regions).filter(([k])=>k!=='custom').map(([k,x])=>'<option value="'+k+'">'+esc(x.name)+'</option>').join('')+'</select></label><label><span>조달 규격 검토</span><select id="regionalFramework"><option value="site">현장 규격 지정</option><option value="iec">IEC 계열 사양·인증 검토</option><option value="ul">UL 계열 사양·인증 검토</option></select></label><label><span>선간 전압 (V) / 단상 전압</span><input id="siteVoltage" type="number" min="1" value="400"></label><label><span>주파수 (Hz)</span><select id="siteFrequency"><option>50</option><option>60</option></select></label><label><span>공급 상수</span><select id="sitePhases"><option value="3">3상 균형 부하</option><option value="1">단상</option></select></label><label><span>PDU 정격 전류 / 상 (A)</span><input id="siteCurrentA" type="number" min="1" value="64"></label><label class="check"><input id="regionPduEnabled" type="checkbox"><span>현장 전원으로 PDU 정격 kW 계산</span></label><label><span>견적 통화</span><select id="quoteCurrency">'+['KRW','USD','EUR','JPY','CNY'].map(x=>'<option>'+x+'</option>').join('')+'</select></label></div><p class="muted">지역별 값은 선택 가능한 전원 예시입니다. 현장 수전·변압기·PDU 실제 사양으로 수정하세요. 규격 검토 선택은 인증 판정이 아닙니다.</p>';
  $('engineering-inputs').append(regions);
  for(const [id,p] of Object.entries(M.presets))$('systemId').insertAdjacentHTML('beforeend','<option value="'+id+'">'+esc(p.name)+'</option>');
  let latest,prices={};try{prices=JSON.parse(localStorage.getItem('dcPlanningPrices')||'{}');}catch{}
  function presetChange(){const p=M.presets[$('systemId').value];$('custom-profile').hidden=!p&&$('systemId').value!=='custom';if(!p){$('acceleratorNote')?.remove();return;}for(const [id,v] of Object.entries({customName:p.name,customGpus:p.gpus,customRU:p.ru,customKw:p.kw,customLinks:p.links,customSpeed:p.speed,customLogicalPerCage:1,customCords:p.cords}))$(id).value=v;$('fabricProtocol').value='Ethernet';$('fabricProtocol').disabled=true;let note=$('acceleratorNote');if(!note){note=document.createElement('p');note.id='acceleratorNote';note.className='muted';$('custom-profile').prepend(note);}note.textContent=p.note;}
  $('systemId').addEventListener('change',()=>{$('fabricProtocol').disabled=false;presetChange();});
  $('regionId').addEventListener('change',()=>{const p=M.regions[$('regionId').value];$('siteVoltage').value=p.voltage;$('siteFrequency').value=p.hz;$('regionalFramework').value=p.framework;$('quoteCurrency').value=p.currency;});
  function card(label,value,note){return '<div class="summaryCard"><span>'+label+'</span><b>'+value+'</b><small>'+note+'</small></div>';}
  function render(r){if(!$('planningSummary'))return;latest=r;if(!r?.usable){for(const id of ['planningSummary','planningValidation','regionalResult','planningPrices'])$(id).innerHTML='';return;}
    const t=r.planningTotals||M.totals(r),currency=r.input.quoteCurrency||'KRW',q=M.quote(r,prices,currency);
    $('planningSummary').innerHTML=card('총 설치 케이블 경로 길이',t.hasRoutes?number(t.routeLengthM)+' m':'미산정',t.hasRoutes?'트렁크 '+number(t.trunkLengthM)+' m · AOC/DAC '+number(t.assemblyLengthM)+' m · P2P 광 '+number(t.p2pLengthM)+' m':'콜로케이션은 테넌트 경로 길이 미입력')+card('구조화·P2P 광 코어 수',t.hasRoutes?number(t.installedFibers)+' F':'미산정','활성 '+number(t.activeFibers)+' F · AOC 내부 심수 미포함')+card('IT / 시설 설계전력',number(t.itKw)+' / '+number(t.facilityKw)+' kW','시설전력 = IT × PUE · 실측 소비전력 아님')+card('예상 BOM 규모',t.bomLines+' 품목',q.priced?number(q.subtotal)+' '+currency+' · '+(q.complete?'전체':'부분')+' 견적 ('+q.priced+'/'+q.total+')':'단가 미입력 · 금액 미산정');
    const rows=r.validation||M.checks(r),official=rows.filter(x=>x.type==='공식 사양'),max=official.length?Math.max(...official.map(x=>x.errorPct??Infinity)):null;
    $('planningValidation').innerHTML='<h3>레퍼런스 검증</h3><p><b>'+(max===null?'공식 서버 사양 오차: 미검증':'공식 서버 사양 최대 상대오차: '+number(max)+'%')+'</b> · 전체 시스템 레퍼런스 대비 오차: <b>미검증</b></p><p class="muted">아래 오차는 서버 공식 사양 및 입력 산식 비교입니다. 토폴로지·시공·실측 검증 결과와 구분됩니다. 검증 기준일: 2026-10-04.</p><details><summary>비교값·출처·오차 보기 ('+rows.length+'항목)</summary><div class="tableWrap"><table><thead><tr><th>항목</th><th>계산값</th><th>기준값</th><th>상대오차</th><th>검증 근거</th></tr></thead><tbody>'+rows.map(x=>'<tr><td>'+esc(x.label)+'</td><td>'+number(x.actual)+' '+esc(x.unit)+'</td><td>'+number(x.expected)+' '+esc(x.unit)+'</td><td>'+(x.errorPct===null?'미산정':number(x.errorPct)+'%')+'</td><td>'+esc(x.type)+(x.source?' · <a href="'+esc(x.source)+'" target="_blank" rel="noopener">공식 출처</a>':'')+'</td></tr>').join('')+'</tbody></table></div></details>';
    const region=r.region;$('regionalResult').innerHTML='<h3>지역 전원·규격 검토</h3><p>'+esc(region?.name)+' · '+esc(region?.voltage)+' V · '+esc(region?.hz)+' Hz · '+esc(region?.phases)+'상 · '+esc(region?.framework)+'</p><p>PDU 정격 '+number(region?.pduRatedKw)+' kW · '+(region?.capacityApplied?'현장 전압·전류·역률로 산정하여 PDU 수량에 반영':'고급 입력의 PDU kW 가정 유지')+'</p><p class="muted">'+esc(region?.status)+'</p>';
    $('planningPrices').innerHTML='<h3>예상 BOM 금액 · '+esc(currency)+'</h3><p class="muted">공급사 견적 단가를 입력하세요. 미입력 품목은 부분 합계에서 제외되며, 통화별 단가를 따로 저장합니다. 세금·운송비·공사비는 미포함입니다.</p><div class="tableWrap"><table><thead><tr><th>품목</th><th>구매 수량</th><th>단가 ('+esc(currency)+')</th><th>금액</th></tr></thead><tbody>'+(r.bom||[]).map(x=>{const key=x.category+' · '+x.item,p=prices[currency]?.[key];return '<tr><td>'+esc(x.item)+'</td><td>'+number(x.qty)+' '+esc(x.unit)+'</td><td><input class="priceInput" type="number" min="0" step="any" aria-label="'+esc(x.item)+' 단가" data-price-key="'+esc(key)+'" value="'+esc(p??'')+'" placeholder="미입력"></td><td>'+((p??'')!==''?number(Number(p)*x.qty):'—')+'</td></tr>';}).join('')+'</tbody></table></div>';
    $('planningPrices').querySelectorAll('input').forEach(el=>el.addEventListener('change',()=>{if(!el.checkValidity())return;prices[currency]??={};prices[currency][el.dataset.priceKey]=el.value;localStorage.setItem('dcPlanningPrices',JSON.stringify(prices));r.planningQuote=M.quote(r,prices,currency);r.planningQuote.currency=currency;render(r);}));r.planningQuote={...q,currency};
  }
  function mount(){
    const result=document.querySelector('.resultPanel'),summary=document.createElement('div');summary.id='planningSummary';summary.className='summaryStrip';result.querySelector('h2').after(summary);
    const validation=document.createElement('section');validation.id='planningValidation';validation.className='planningValidation';$('topologySvg').before(validation);
    const region=document.createElement('section');region.id='regionalResult';region.className='panel';$('view-power').prepend(region);
    const pricing=document.createElement('section');pricing.id='planningPrices';pricing.className='panel';$('view-bom').append(pricing);
    const hint=document.createElement('p');hint.className='muted';hint.textContent='길이는 설치 케이블 본선·통합 케이블 기준입니다. 예비 재고, 포설 여유, 패치 리드 미실측 길이·AOC 내부 심수는 제외됩니다.';summary.after(hint);
    const basic=document.createElement('div');basic.id='basicInputs';const adv=document.querySelector('.formPanel .advanced');document.querySelector('.formPanel>.fields').before(basic);
    const basicIds=new Set(['targetGPU','systemId','topology','rackPowerKw','coolingMode','serverDistanceM','leafSpineDistanceM']);
    const main=document.createElement('section');main.className='inputGroup';main.innerHTML='<h3>기본 입력</h3><div class="fields sub"></div>';basic.append(main);
    document.querySelectorAll('.formPanel>.fields .inputGroup').forEach(group=>{group.querySelectorAll('label').forEach(label=>{if([...label.querySelectorAll('input,select')].some(x=>basicIds.has(x.id)))main.querySelector('.fields').append(label);});if(group.querySelector('input,select'))adv.append(group);else group.remove();});
    document.querySelector('.formPanel>.fields').hidden=true;adv.querySelector('summary').textContent='고급 입력 · 포트·랙·광손실·지역 규격';
    const toggle=document.createElement('button');toggle.type='button';toggle.id='inputMode';toggle.textContent='고급형 보기';toggle.setAttribute('aria-expanded','false');toggle.onclick=()=>{adv.open=!adv.open;toggle.setAttribute('aria-expanded',String(adv.open));toggle.textContent=adv.open?'기본형 보기':'고급형 보기';};basic.prepend(toggle);adv.addEventListener('toggle',()=>{toggle.setAttribute('aria-expanded',String(adv.open));toggle.textContent=adv.open?'기본형 보기':'고급형 보기';});
    const custom=$('custom-profile');custom.parentNode.removeChild(custom);basic.append(custom); // Preset assumptions stay visible even in basic mode.
    const tips={topology:'Rail: 가속기 연결을 병렬 Fabric으로 분리. Clos: Leaf–Spine–Core 계층. ToR: 랙 단위 스위치.',fabricProtocol:'InfiniBand 또는 Ethernet 패브릭. 범용 링크 수 계산이며 공급사 호환성 확인 필요.',podLeafLimit:'Pod는 네트워크 설계 묶음이며 Pod당 Leaf 스위치 수의 상한입니다.',targetPodEgress:'Pod 다운링크/업링크 대역폭 비율. 4는 4:1이며 전체 GPU 대역폭의 1/4이 외부 업링크 목표입니다.',rackRU:'RU는 랙 높이 단위입니다. 1 RU = 44.45 mm.',oversub:'다운링크/업링크 대역폭 비율. 1은 1:1이며 혼잡 가능성을 보장하지는 않습니다.',pue:'시설 전체 전력 ÷ IT 장비 전력. 사이트의 계획 가정 또는 실측값을 입력하세요.',powerFactor:'유효전력(kW)/피상전력(kVA). 지역 PDU 전류 계산에도 적용합니다.',trunkFiberCount:'물리 트렁크 한 개의 설치 심수. 활성 심수와 커넥터가 요구하는 설치 심수는 다릅니다.',matedPairs:'경로상 서로 체결된 커넥터 쌍 수. 구조화 광 채널 손실에 반영됩니다.',marginDb:'오염·노화·시공 불확실성에 대비한 계획 광손실 여유.',pduRatedKw:'PDU 하나의 정격 유효전력. 현장 전원 계산 체크 시 전압·전류·역률로 대체됩니다.',pduUtilPct:'PDU 정격 중 계획상 사용하는 비율. A/B 각 측에 전체 랙 부하를 수용하도록 산정합니다.',regionPduEnabled:'단상 VI·PF 또는 균형 3상 √3·V선간·I·PF로 PDU kW를 계산하고 수량을 다시 산정합니다.',siteFrequency:'지역 전원 예시로 50/60 Hz를 선택합니다. 모델은 주파수로 전력 변환을 하지 않습니다.',customLinks:'사용자가 가정한 노드당 외부 논리 링크 수(1–8). 가속기 내부 링크·Gaudi 고유 패브릭 재현이 아닙니다.',customKw:'노드 전체 설계전력. 가속기 TDP 합계와 다르며 CPU·메모리·NIC·냉각 부하 포함 값을 확인하세요.',serverCabling:'구조화 배선은 트렁크/패널을 경유하며 점대점은 장비 사이 직접 연결입니다.',coolingMode:'선택한 방식의 용량 계획. 서버가 해당 냉각 방식과 실제 호환되는지 별도 확인하세요.'};
    for(const [id,text] of Object.entries(tips)){const label=$(id)?.closest('label');if(!label)continue;const d=document.createElement('details');d.className='fieldTooltip';d.innerHTML='<summary aria-label="'+esc(text)+'">?</summary><span>'+esc(text)+'</span>';label.append(d);}
    if(window.DCDesign)render(window.DCDesign);
  }
  document.addEventListener('dc:design',e=>render(e.detail));
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>requestAnimationFrame(mount),{once:true});else requestAnimationFrame(mount);
})();
