(() => {
'use strict';
const VERSION='7.3.2';
const textOf=e=>(e&&(e.innerText||e.textContent)||'').replace(/\s+/g,' ').trim();
const state={design:null};
const L={
ko:{ex:'Export Excel',need:'설계 계산 후 다시 시도해 주세요.',fail:'Excel 내보내기에 실패했습니다.',channels:'한국 구매 / 기술 문의 채널',channelSub:'BOM 관련 업체 중 공개자료로 확인 가능한 한국 법인·공식 총판·유통 채널입니다.',datasheet:'데이터시트'},
en:{ex:'Export Excel',need:'Please run the design calculation first.',fail:'Failed to export Excel.',channels:'Korea Purchasing / Technical Contacts',channelSub:'Publicly verified Korean offices, official distributors and product channels for BOM vendors.',datasheet:'Datasheet'},
ja:{ex:'Excel出力',need:'先に設計計算を実行してください。',fail:'Excel出力に失敗しました。',channels:'韓国の購入 / 技術問い合わせ先',channelSub:'BOMベンダーの韓国法人、公式ディストリビューター、公開確認済みチャネルです。',datasheet:'データシート'},
zh:{ex:'导出 Excel',need:'请先执行设计计算。',fail:'Excel 导出失败。',channels:'韩国采购 / 技术联系渠道',channelSub:'面向BOM厂商的公开可验证韩国法人、官方分销商及渠道。',datasheet:'数据表'},
de:{ex:'Excel exportieren',need:'Bitte zuerst die Designberechnung ausführen.',fail:'Excel-Export fehlgeschlagen.',channels:'Korea Einkauf / Technische Kontakte',channelSub:'Öffentlich verifizierte koreanische Niederlassungen, offizielle Distributoren und Vertriebskanäle.',datasheet:'Datenblatt'}
};
function token(s){s=String(s||'').trim().toLowerCase();if(s.includes('한국')||s.includes('korean')||s==='ko'||s==='kr')return'ko';if(s.includes('日本')||s.includes('japanese')||s==='ja'||s==='jp')return'ja';if(s.includes('中文')||s.includes('chinese')||s==='zh'||s==='cn')return'zh';if(s.includes('deutsch')||s.includes('german')||s==='de')return'de';if(s.includes('english')||s==='en')return'en';return null}
function remember(el){if(!el)return null;const a=el.getAttribute?((el.getAttribute('data-lang')||'')+' '+(el.getAttribute('data-language')||'')+' '+(el.getAttribute('lang')||'')):'';const x=token(a+' '+(el.value||'')+' '+textOf(el));if(x){window.__dcBomUiLang=x;document.documentElement.setAttribute('data-dc-bom-ui-lang',x)}return x}
function lang(){if(window.__dcBomUiLang&&L[window.__dcBomUiLang])return window.__dcBomUiLang;const s=document.documentElement.getAttribute('data-dc-bom-ui-lang');if(s&&L[s])return s;for(const e of document.querySelectorAll('[data-lang].active,[data-language].active,[aria-pressed="true"],button.active,.lang.active,.language.active')){const x=remember(e);if(x)return x}for(const sel of document.querySelectorAll('select')){const o=sel.options&&sel.options[sel.selectedIndex];const x=remember(o)||remember(sel);if(x)return x}return token(document.documentElement.lang)||'ko'}
const tr=()=>L[lang()]||L.ko;
function findCalc(){return Array.from(document.querySelectorAll('button,input[type="button"],input[type="submit"]')).find(e=>{const s=(e.value||textOf(e)).toLowerCase();return(s.includes('설계')&&s.includes('계산'))||s.includes('calculate')||s.includes('design calculation')||s.includes('計算')||s.includes('设计计算')||s.includes('berechnen')})||null}
function inputs(){const out=[];for(const e of document.querySelectorAll('input,select,textarea')){let k='';if(e.id){const l=document.querySelector('label[for="'+CSS.escape(e.id)+'"]');if(l)k=textOf(l)}if(!k&&e.closest('.field')){const l=e.closest('.field').querySelector('label');if(l)k=textOf(l)}if(!k)continue;let v='';if(e.tagName==='SELECT'){const o=e.options[e.selectedIndex];v=o?textOf(o):e.value}else if(e.type==='checkbox'||e.type==='radio')v=e.checked?'true':'false';else v=e.value;out.push({field:k,value:String(v||'')})}return out.slice(0,400)}
function summary(){const out=[];for(const e of document.querySelectorAll('.metric,.kpi,.archMini,.osa-kpi')){const k=e.querySelector('.k,.label,.title'),v=e.querySelector('.v,.value');if(k&&v&&textOf(k))out.push({field:textOf(k),value:textOf(v)})}for(const id of ['uxSystem','uxFabric','uxRack','uxMedia','uxCooling','uxStatus']){const e=document.getElementById(id);if(e&&textOf(e))out.push({field:id,value:textOf(e)})}return out.slice(0,400)}
function cell(c){return{text:textOf(c),links:Array.from(c.querySelectorAll('a[href]')).map(a=>({label:textOf(a)||'Link',url:a.href})).filter(x=>/^https?:/i.test(x.url))}}
function tableData(tb){if(!tb)return{rows:[[{text:'-',links:[]}]]};const rows=Array.from(tb.querySelectorAll('tr')).map(r=>Array.from(r.children).filter(c=>c.tagName==='TH'||c.tagName==='TD').map(cell)).filter(r=>r.length);return{rows:rows.length?rows:[[{text:'-',links:[]}]]}}
function findTable(rx){for(const h of document.querySelectorAll('h1,h2,h3,h4,h5,summary,.phaseBand,.section-title,.card-title')){if(!rx.test(textOf(h)))continue;const s=h.closest('.card,.panel,section,article,details')||h.parentElement;if(s&&s.querySelector('table'))return s.querySelector('table');let n=h.nextElementSibling;for(let i=0;n&&i<8;i++,n=n.nextElementSibling){if(n.matches&&n.matches('table'))return n;if(n.querySelector&&n.querySelector('table'))return n.querySelector('table')}}return null}
function payload(){return{version:VERSION,language:lang(),requirements:inputs(),designResult:summary(),genericBom:tableData(findTable(/generic\s*bom|일반\s*bom|범용\s*bom|汎用.*bom|通用.*bom/i)),receipt:tableData(findTable(/제품.*매칭.*영수증|product.*match.*receipt|product.*receipt|製品.*マッチ|产品.*匹配|produkt.*matching/i)),design:state.design}}
function hasDesign(){return !!state.design||['mGpu','mComputeRacks','mLeafs','mSpines'].some(id=>{const e=document.getElementById(id);return e&&textOf(e)&&textOf(e)!=='-'})}
async function exportExcel(){const t=tr();if(!hasDesign()){alert(t.need);return}try{const r=await fetch('/api/export-xlsx',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});if(!r.ok)throw 0;const b=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='data-center-bom-design-v'+VERSION+'.xlsx';document.body.appendChild(a);a.click();const u=a.href;a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch{alert(t.fail)}}
const CHANNELS=[
['Corning','남해이엔지 (Namhae ENG)','Corning 관련 국내 취급 / 기술 문의 채널','경기도 성남시 중원구 갈마치로 288번길 14, 331호 (상대원동, 성남SK V1 타워)','https://www.nhelec.com/modules/catalogue/cg_view.html?cc=15&no=47','nheng01130@nheng.kr','mailto:nheng01130@nheng.kr'],
['Corning','대신엔에스 (Daeshin NS)','Official optical-communications distributor','401 Daeshin Bldg., 448 Cheonhodaero, Seongdong-gu, Seoul 04808','http://www.ds-ns.net/','070-7013-0005','tel:070-7013-0005'],
['Corning','한국코닝 (Corning Korea)','Official Korea office','5F/6F Gangnam Finance Center, 152 Teheran-ro, Gangnam-gu, Seoul 06236','https://www.corning.com/kr/ko/about-us/company-profile/corning-in-korea/locations-in-korea.html','02-796-9500','tel:02-796-9500'],
['Sumitomo Electric','스미토모 코리아','Official group company / cable sales','14F Gyeongwon Bldg., 340 Gangnam-daero, Gangnam-gu, Seoul 06242','https://sumitomoelectric.com/company/office_group_companies/sumitomo-electric-korea-electronics-ltd','02-3453-4511','tel:02-3453-4511'],
['Supermicro','슈퍼마이크로컴 코리아','Official Korea office','#1001 Trade Tower, 511 Yeongdong-daero, Gangnam-gu, Seoul 06164','https://www.supermicro.com/en/about/contact','02-554-0045','tel:+82-2-554-0045'],
['Juniper','(주)인성 디지탈','공식 총판 / 구매·기술 문의','서울특별시 송파구 위례성대로 22길 28 (오금동, S2F빌딩) 3, 4층','https://www.isd.co.kr/','junipersalesgroup@isd.co.kr','mailto:junipersalesgroup@isd.co.kr'],
['Juniper','(주)시엔스','공식 총판 / 구매·기술 문의','서울특별시 강남구 테헤란로 44길 8, 8층(역삼동,아이콘역삼빌딩)','https://www.sciens21.com/','sales@sciens21.com','mailto:sales@sciens21.com'],
['Juniper','(주)투케이엠시스템즈','공식 총판 / 구매·기술 문의','서울특별시 서초구 남부순환로 2395 호경빌딩 3층','https://twokm.co.kr/','twokm@twokm.co.kr','mailto:twokm@twokm.co.kr'],
['Cisco','시스코 코리아','Official Korea office','5F ASEM Tower, 517 Yeongdong-daero, Gangnam-gu, Seoul 06164','https://www.cisco.com/site/us/en/about/contact-cisco/global-office-locations.html','02-3429-8000','tel:+82-2-3429-8000']
];
const DS=[
[/QFX5240/i,'https://www.juniper.net/content/dam/www/assets/datasheets/us/en/switches/qfx5240-line-of-switches-datasheet.pdf'],
[/N9364E[- ]?SG2/i,'https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus-9364e-sg2-switch-ds.html'],
[/N9364E[- ]?SP2R/i,'https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus-9364e-sp2r-switches-ds.html'],
[/DGX\s*B200/i,'https://docs.nvidia.com/dgx/dgxb200-user-guide/introduction-to-dgxb200.html'],
[/ConnectX[- ]?7/i,'https://docs.nvidia.com/nvidia-connectx-7-adapter-cards-user-manual.pdf'],
[/EDGE8/i,'https://ecatalog.corning.com/optical-communications/US/en/Fiber-Optic-Cable-Assemblies/Indoor-Cable-Assemblies/Multifiber-Indoor-Cable-Assemblies/EDGE8%C2%AE-MTP%C2%AE-Trunk/p/edge8-mtp-trunk-cable?variant=fiber-count-8'],
[/Sumitomo|FREEFORM RIBBON/i,'https://sumitomoelectric.com/products/optical-cables']
];
function enrichReceipt(){const tb=findTable(/제품.*매칭.*영수증|product.*match.*receipt|product.*receipt|製品.*マッチ|产品.*匹配|produkt.*matching/i);if(!tb)return;const head=tb.querySelector('tr');if(!head)return;const hs=Array.from(head.children).map(x=>textOf(x).toLowerCase());let ai=hs.findIndex(x=>/alternative|대안|대체|候補|替代/.test(x));if(ai<0)ai=hs.length-1;for(const trr of Array.from(tb.querySelectorAll('tr')).slice(1)){const cs=Array.from(trr.children);if(!cs[ai]||cs[ai].querySelector('.v47-ds'))continue;const row=textOf(trr);if(/leaf|spine|switch|스위치|スイッチ|交换机/i.test(row)&&!/Juniper|QFX5240/i.test(textOf(cs[ai]))){const j=document.createElement('div');j.className='v47-alt';j.innerHTML='Juniper: QFX5240-64OD / QFX5240-64QD · <a href="https://www.juniper.net/content/dam/www/assets/datasheets/us/en/switches/qfx5240-line-of-switches-datasheet.pdf" target="_blank" rel="noopener">Datasheet</a>';cs[ai].appendChild(j)}const m=DS.find(x=>x[0].test(row+' '+textOf(cs[ai])));const d=document.createElement('div');d.className='v47-ds';d.innerHTML=tr().datasheet+': '+(m?'<a href="'+m[1]+'" target="_blank" rel="noopener">Link</a>':'-');cs[ai].appendChild(d)}}
function addJuniper(){const body=document.getElementById('osaSwitches');if(!body||body.querySelector('[data-v47-juniper]'))return;const rows=[['QFX5240-64OD','64 × 800G OSFP','128×400G / 256×200G / 256×100G','2RU','613 W / 2,198 W'],['QFX5240-64QD','64 × 800G QSFP-DD','128×400G / 256×200G / 320×100G / 256×50G','2RU','616 W / 2,258 W']];for(const r of rows){const trr=document.createElement('tr');trr.setAttribute('data-v47-juniper','1');trr.innerHTML='<td>Juniper</td><td>'+r[0]+'</td><td>'+r[1]+'</td><td>'+r[2]+'</td><td>'+r[3]+'</td><td>'+r[4]+'</td><td>AI leaf / spine / super-spine · RoCEv2</td><td><a href="https://www.juniper.net/content/dam/www/assets/datasheets/us/en/switches/qfx5240-line-of-switches-datasheet.pdf" target="_blank" rel="noopener">Datasheet</a></td>';body.appendChild(trr)}const card=body.closest('.osa-card');if(card){const title=card.querySelector('.osa-title');if(title)title.textContent='Switch equipment candidates · Cisco / Juniper'}}
function contactHtml(x){if(!x||!x[5]||x[5]==='-')return'-';const href=x[6]||(x[5].includes('@')?'mailto:'+x[5]:'tel:'+String(x[5]).replace(/\s+/g,''));return'<a href="'+href+'">'+x[5]+'</a>'}
function channelPanel(){let p=document.getElementById('v47-channels');if(!p){p=document.createElement('section');p.id='v47-channels';const a=document.getElementById('design-example-cell')||document.getElementById('v47-actions');if(a)a.insertAdjacentElement('afterend',p);else(document.querySelector('main,.wrap,.container')||document.body).appendChild(p)}const l=lang();if(p.getAttribute('data-v47-lang')===l&&p.children.length)return;const t=tr();p.setAttribute('data-v47-lang',l);p.innerHTML='<div class="v47-channel-head"><h3>'+t.channels+'</h3><div>'+t.channelSub+'</div></div><table><thead><tr><th>Vendor</th><th>Channel</th><th>Type</th><th>Address</th><th>URL</th><th>Contact</th></tr></thead><tbody>'+CHANNELS.map(x=>'<tr><td>'+x[0]+'</td><td>'+x[1]+'</td><td>'+x[2]+'</td><td>'+x[3]+'</td><td><a href="'+x[4]+'" target="_blank" rel="noopener">Open</a></td><td>'+contactHtml(x)+'</td></tr>').join('')+'</tbody></table>'}
function mount(){if(!document.getElementById('v47-actions')){const calc=findCalc();if(calc){let row=calc.closest('.design-action-row');if(!row){row=document.createElement('div');row.className='design-action-row';calc.parentNode.insertBefore(row,calc);row.appendChild(calc)}const m=document.createElement('div');m.id='v47-actions';m.innerHTML='<button type="button" class="v47-export"></button>';row.appendChild(m);m.querySelector('.v47-export').onclick=exportExcel}}const m=document.getElementById('v47-actions');if(m)m.querySelector('.v47-export').textContent=tr().ex;channelPanel();enrichReceipt();addJuniper()}
const nativeFetch=window.fetch;if(nativeFetch&&!window.__v47Fetch){window.__v47Fetch=true;window.fetch=async function(...args){const r=await nativeFetch.apply(this,args);try{const u=String(args[0]&&args[0].url?args[0].url:args[0]||'');if(u.includes('/api/design'))r.clone().json().then(x=>state.design=x).catch(()=>{})}catch{}return r}}
function start(){let lastLang=lang();mount();document.addEventListener('click',e=>{const q=e.target&&e.target.closest&&e.target.closest('button,a,[role="button"],[data-lang],[data-language]');if(q)remember(q);setTimeout(()=>{const l=lang();if(l!==lastLang){lastLang=l;mount()}else if(!document.getElementById('v47-actions'))mount()},60)},true);document.addEventListener('change',e=>{if(e.target&&e.target.tagName==='SELECT'){const o=e.target.options[e.target.selectedIndex];remember(o);remember(e.target)}setTimeout(()=>{const l=lang();if(l!==lastLang){lastLang=l;mount()}},30)},true);let attempts=0;const boot=setInterval(()=>{attempts++;if(document.getElementById('v47-actions')||attempts>20)clearInterval(boot);mount()},500);setInterval(()=>{const l=lang();if(l!==lastLang){lastLang=l;mount()}else{enrichReceipt();addJuniper()}},1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();