const {JSDOM,VirtualConsole}=require(process.env.DCBOM_JSDOM_PATH||'jsdom');
const assert=require('node:assert/strict');
(async()=>{
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 const dom=new JSDOM(require('fs').readFileSync('index.html','utf8').replace(/<script src="\.\/([^"]+)"><\/script>/g,(_,file)=>file.startsWith('exceljs')?'':'<script>'+require('fs').readFileSync(file.split('?')[0],'utf8')+'</script>'),{url:'http://localhost:8765/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.eval(require('fs').readFileSync(process.env.DCBOM_EXCELJS_PATH||'./exceljs.min.js','utf8'));w.fetch=global.fetch;w.Response=global.Response;w.Headers=global.Headers;w.URL.createObjectURL=()=>'';}});
 const w=dom.window,d=w.document,$=id=>d.getElementById(id),wait=async pred=>{for(let i=0;i<300;i++){if(pred())return;await new Promise(r=>setTimeout(r,10));}console.log({errors,ready:d.readyState,design:w.DCDesign,planning:$('planningSummary')?.outerHTML});throw Error('DOM condition timeout')},change=(id,value)=>{$(id).value=value;$(id).dispatchEvent(new w.Event('change',{bubbles:true}));},run=async()=>{$('run').click();await wait(()=>!$('run').disabled);await new Promise(r=>setTimeout(r,30));};
 await wait(()=>$('completeness-summary')?.children.length===2);

 await wait(()=>$('design-products')?.querySelector('table'));
 const base={...w.getEngineeringInputs(),systemId:'h200',frontendEnabled:false,oobEnabled:false};const design=patch=>w.DCBOMRunScenario({...base,...patch});
 let r=design({serverDistanceM:100,uplinkBase:'8',serverBase:'8'});assert.ok(r.usable);assert.equal(r.optical.server.profile.installedChannelFibers,8);assert.equal(r.optical.server.profile.connector,'MPO-12/APC');assert.equal(r.optical.leafSpine.profile.trunkFiberCount,16);
 r=design({serverDistanceM:100,uplinkBase:'12',serverBase:'12'});assert.ok(r.usable);assert.equal(r.optical.server.profile.installedChannelFibers,12);assert.equal(r.optical.server.profile.trunkFiberCount,24);assert.equal(r.optical.leafSpine.trunk.provisionedFibers,r.optical.leafSpine.trunk.installedCableCount*24);assert.ok(r.productRequirements.some(q=>q.candidates.some(c=>c.vendor==='YOFC'&&c.kind==='fiber')));
 assert.equal(design({serverDistanceM:100,serverBase:'16'}).usable,false);assert.equal(design({serverMedia:'sr',fiberPreference:'mmf',serverBase:'12',uplinkMedia:'sr'}).usable,false);
 r=design({systemId:'b300',serverDistanceM:100,serverBase:'16',uplinkBase:'16'});assert.ok(r.usable);assert.equal(r.optical.server.profile.installedChannelFibers,16);assert.equal(r.optical.server.profile.connector,'MPO-16/APC');assert.equal(r.optical.server.profile.connectorGroups,1);
 r=design({systemId:'b300',serverDistanceM:100,serverBase:'12',uplinkBase:'12',trunkFiberCount:24});assert.ok(r.usable);assert.equal(r.optical.server.profile.installedChannelFibers,24);assert.equal(r.optical.server.profile.connectorGroups,2);
 assert.equal(design({serverMedia:'fr',serverBase:'12',serverDistanceM:600}).usable,false);r=design({serverMedia:'fr',serverBase:'auto',serverDistanceM:600});assert.ok(r.usable);assert.equal(r.optical.server.profile.base,2);assert.ok(r.productRequirements.filter(q=>q.segment==='server').every(q=>!q.candidates.some(c=>c.kind==='connector')));
 assert.equal(design({fiberPatchM:-1}).usable,false);
 r=design({frontendEnabled:true,oobEnabled:true});assert.ok(r.powerProof.residualKw<1e-8);assert.ok(r.productRequirements.some(q=>q.candidates.some(c=>c.kind==='copper')));assert.ok(r.productRequirements.some(q=>q.candidates.some(c=>c.kind==='lc')));assert.equal(r.productRequirements.filter(q=>q.cable&&q.unit==='channel'&&/patch|harness/i.test(q.item)).reduce((sum,q)=>sum+q.installed*q.lengthM,0),4096);assert.ok(r.productRequirements.filter(q=>q.unit==='module'||q.unit==='panel').every(q=>q.lengthM===null));assert.equal(r.powerProof.totalRacks,r.summary.totalRacks);assert.equal(r.powerProof.facilityKw,r.summary.totalItPowerKw*r.input.pue);assert.ok(w.DCProductCsv(r).includes('official_sources'));assert.ok(w.DCProductCsv(r).includes('yofc.com'));
 assert.equal(w.DCOfficialEvents.companies.length,12);assert.ok(w.DCOfficialEvents.filter({today:'2026-10-03'}).every(e=>e.end>='2026-10-03'));assert.ok(w.DCOfficialEvents.filter({past:true,today:'2026-10-03'}).some(e=>e.end<'2026-10-03'));
 $('tab-events').click();assert.equal($('view-events').hidden,false);assert.equal($('eventSources').querySelectorAll('tbody tr').length,12);change('eventCompany','US Conec');assert.equal(w.DCDesignStale,false);assert.equal($('eventResults').querySelectorAll('tbody tr').length,0);$('eventPast').checked=true;$('eventPast').dispatchEvent(new w.Event('change'));assert.ok($('eventResults').querySelectorAll('tbody tr').length>0);
 $('tab-power').click();$('pueEnergyIT').value='2000';$('pueEnergyFacility').value='3000';$('pueEnergyIT').dispatchEvent(new w.Event('input'));$('pueEnergyIT').dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(w.DCDesignStale,false);assert.ok($('pueEnergyResult').textContent.includes('1.5'));assert.ok($('power-proof').textContent.includes('38 랙'));
 change('targetGPU','0');await run();assert.equal($('design-products').textContent,'');assert.equal($('power-proof').textContent,'');change('targetGPU','1024');await run();assert.ok($('design-products').querySelector('table'));assert.deepEqual(errors,[]);

 const response=await w.fetch('/api/export-xlsx',{method:'POST',body:JSON.stringify({design:w.DCDesign})});assert.equal(response.status,200);const bytes=Buffer.from(await response.arrayBuffer());assert.ok(bytes.length>10000);const book=new w.ExcelJS.Workbook();await book.xlsx.load(w.Uint8Array.from(bytes));assert.equal(book.worksheets.length,11);assert.equal(book.getWorksheet('8_Product Requirements').rowCount,w.DCDesign.bom.length+1);assert.equal(book.getWorksheet('11_Official Events').rowCount,w.DCOfficialEvents.entries.length+1);const trunkRow=book.getWorksheet('8_Product Requirements').getRows(2,100).find(row=>row.getCell(6).value==='trunk');assert.equal(trunkRow.getCell(8).value,'24');assert.equal(trunkRow.getCell(7).value,'100');console.log(JSON.stringify({exportPass:true,bytes:bytes.length,sheets:book.worksheets.map(s=>s.name)}));
 console.log(JSON.stringify({passed:true,tests:'Base-8/12/16 physical fibers, per-route trunk packing, incompatible interfaces, LC/copper product filtering, rack/power proof, CSV, 12-company event coverage/filter, energy PUE calculator, invalid result clearing',errors}));dom.window.close();
})().catch(e=>{console.error(e);process.exit(1)});