(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels = {targetGPU:'요구 GPU 수',systemId:'서버 프로파일',topology:'네트워크 토폴로지',fabricProtocol:'Fabric 프로토콜',procurementTier:'조달 정책',podLeafLimit:'Pod당 Leaf 상한',targetPodEgress:'Pod 업링크 비율 목표',rackRU:'랙 높이 (RU)',rackPowerKw:'랙 전력 한도 (kW)',rackCoolingKw:'랙 냉각 한도 (kW)',coolingMode:'냉각 방식',serverDistanceM:'서버–Leaf 거리 (m)',leafSpineDistanceM:'Leaf–Spine 거리 (m)',serverCabling:'서버–Leaf 배선',leafSpineCabling:'Leaf–Spine 배선',trunkFiberCount:'트렁크 규격 (심수)',sparePct:'예비 수량 (%)'};
  const names = [['result','설계 결과'],['optical','광배선'],['power','전력·냉각'],['bom','BOM·견적'],['evidence','근거·검토']];
  let panels = {}, allRoutes = [], page = 0, latest;
  function build() {
    const main = document.querySelector('main.grid'), form = document.querySelector('.formPanel'), result = document.querySelector('.resultPanel');
    if (!main || !form || !result) return;
    const h1=document.querySelector('header h1'),subtitle=document.querySelector('header p'),scopeNote=document.querySelector('.security span');if(h1)h1.textContent='데이터센터 케이블 설계';if(subtitle)subtitle.textContent='요구조건에서 광·전력·자재 산출까지';if(scopeNote)scopeNote.textContent='결과는 입력한 가정에 따른 계획 산출입니다. 실제 제품 호환성, 시공 경로와 LS 품목 코드는 별도 검토가 필요합니다.';
    const grid = form.querySelector(':scope > .fields'), original = [...grid.querySelectorAll(':scope > label')];
    const groups = [['기본 요구조건',['targetGPU','systemId','topology','fabricProtocol','procurementTier']],['Fabric·포트 정책',['podLeafLimit','targetPodEgress']],['랙·냉각 한도',['rackRU','rackPowerKw','rackCoolingKw','coolingMode']],['배선 구간',['serverDistanceM','leafSpineDistanceM','serverCabling','leafSpineCabling','trunkFiberCount','sparePct']]];
    grid.replaceChildren();
    groups.forEach(([title, ids]) => { const section=document.createElement('section'); section.className='inputGroup'; section.innerHTML='<h3>'+title+'</h3><div class="fields sub"></div>'; const inner=section.querySelector('.fields'); ids.forEach(id=>{const label=original.find(x=>x.querySelector('#'+id));if(label){const span=label.querySelector(':scope > span');if(span)span.textContent=labels[id];inner.append(label)}});grid.append(section); });
    const scenario=document.createElement('label');scenario.className='scopeSelect';scenario.innerHTML='<span>설계 범위</span><select id="wb-scenario"><option value="ai">AI·GPU 클러스터</option><option value="colo">콜로케이션 용량 계획</option></select>';form.querySelector('h2').after(scenario);
    const hiddenMode=document.createElement('select');hiddenMode.id='v65-mode';hiddenMode.hidden=true;hiddenMode.innerHTML='<option value="ai">AI</option><option value="colo">Colocation</option>';form.append(hiddenMode);
    const colo=document.createElement('details');colo.className='coloInputs';colo.innerHTML='<summary>콜로케이션 입력</summary><div class="fields sub"><label><span>테넌트 수</span><input id="v65-tenants" type="number" min="1" value="4"></label><label><span>테넌트당 랙</span><input id="v65-racks" type="number" min="1" value="20"></label><label><span>랙당 IT 부하 (kW)</span><input id="v65-density" type="number" min="1" value="12" step="0.5"></label><label><span>전력 여유율 (%)</span><input id="v65-reserve" type="number" min="0" value="20"></label><label><span>통신사 경로/테넌트</span><input id="v65-carriers" type="number" min="1" value="2"></label></div>';scenario.insertAdjacentElement('afterend',colo);
    const shell=document.createElement('div');shell.id='workbench-shell';const nav=document.createElement('nav');nav.id='workbench-nav';nav.setAttribute('aria-label','설계 정보');nav.innerHTML='<button type="button" class="jumpInput">요구조건</button>'+names.map(([id,name],i)=>'<button type="button" role="tab" id="tab-'+id+'" aria-selected="'+(i===0)+'" aria-controls="view-'+id+'" data-view="'+id+'">'+name+'</button>').join('')+'<button type="button" id="exportWorkbook" class="exportButton">Excel 내보내기</button>';
    const upper=document.createElement('div');upper.className='workbench-top';const views=document.createElement('div');views.id='workbench-content';
    for(const [id] of names){const p=document.createElement('section');p.className='workbench-view';p.id='view-'+id;p.setAttribute('role','tabpanel');p.setAttribute('aria-labelledby','tab-'+id);p.hidden=id!=='result';views.append(p);panels[id]=p;}
    upper.append(form,views);shell.append(nav,upper);main.replaceWith(shell);panels.result.append(result);
    panels.optical.innerHTML='<div id="cable-summary" class="summaryStrip"></div><section class="panel"><h2>구간별 케이블 스케줄</h2><p class="muted">포트 번호는 계산상 논리 포트 일련번호입니다. 실제 스위치 cage/breakout, pin·극성, 여유장과 트레이 경로는 제품 선정·시공 단계에서 확인해야 합니다.</p><div class="tableWrap"><table class="scheduleTable"><thead><tr><th>구간</th><th>연결 경로 (장비·랙·논리 포트)</th><th>매체·커넥터</th><th>길이</th><th>링크</th><th>Active / 설치 심수</th><th>트렁크</th><th>손실 / 예산</th></tr></thead><tbody id="scheduleBody"></tbody></table></div><div class="pager"><button id="schedulePrev">이전</button><span id="schedulePage"></span><button id="scheduleNext">다음</button></div></section><div id="opticalDetails"></div>';
    panels.power.innerHTML='<div id="powerSummary" class="summaryStrip"></div><section class="panel"><h2>랙별 전력·PDU</h2><div class="tableWrap"><table><thead><tr><th>랙</th><th>역할</th><th>장비 수</th><th>사용 RU</th><th>IT 부하 (kW)</th><th>A/B PDU</th></tr></thead><tbody id="rackBody"></tbody></table></div></section><section class="panel"><h2>시설 용량 시나리오</h2><div id="facilityPanel"></div></section><div id="coolingTarget"></div><div id="rackTarget"></div>';
    panels.bom.innerHTML='<div id="bomSummary" class="summaryStrip"></div><section class="panel"><h2>설치·예비·구매 수량</h2><p class="muted">구매 수량은 설계 BOM 값을 유지합니다. 설치와 예비 수량은 항목별 계산 근거가 있을 때만 분리하며, 미분리 항목은 검토 상태로 표시합니다.</p><div class="tableWrap"><table><thead><tr><th>품목</th><th>규격·산정 근거</th><th>설치</th><th>예비</th><th>구매</th><th>상태</th></tr></thead><tbody id="quoteBomBody"></tbody></table></div></section><section class="panel"><h2>LS 제품·견적 연결</h2><p class="muted">확인된 LS 품목코드와 공식 사양 URL을 입력하면 이 브라우저에 저장됩니다. 수기 입력만으로 제품 호환성이 검증되지는 않습니다.</p><div class="tableWrap"><table><thead><tr><th>자재</th><th>수량</th><th>LS 품목코드</th><th>공식 사양 URL</th><th>상태</th></tr></thead><tbody id="skuBody"></tbody></table></div></section>';
    panels.evidence.innerHTML='<div id="sourceCard"></div><div id="ls-product-data"></div><div id="auditTarget"></div><div id="evidenceTarget"></div>';
    const advanced=document.createElement('details');advanced.className='advanced';advanced.innerHTML='<summary>상세 가정·고급 입력</summary>';form.querySelector('#run').before(advanced);if($('engineering-inputs'))advanced.append($('engineering-inputs'));
    form.querySelectorAll(':scope > details:not(.advanced):not(.coloInputs)').forEach((d,i)=>{const s=d.querySelector('summary');if(s)s.textContent=i?'운영 장비 옵션':'시설 전력·스토리지'});
    const detailLabels={facilityEnabled:'UPS·발전기·변압기 산정',facilityRedundancy:'시설 이중화',storageEnabled:'스토리지 포함',storageCapacityTb:'스토리지 용량 (TB)',storageProtocol:'스토리지 프로토콜',storageEndpointPorts:'스토리지 종단 포트',enterpriseRackEnabled:'운영 보조장비 포함',firewallQty:'방화벽 수량',routerQty:'라우터 수량',loadBalancerQty:'로드밸런서 수량',kvmQty:'KVM 수량',nasQty:'NAS 수량'};
    for(const [id,text] of Object.entries(detailLabels)){const label=$(id)?.closest('label');if(label){const span=label.querySelector('span');if(span)span.textContent=text;}}
    for(const [id,map] of Object.entries({procurementTier:{premium:'성능 우선',balanced:'균형',value:'비용 우선'},coolingMode:{auto:'자동 · 서버 공랭 유지',air:'공랭', 'rear-door':'후면 도어 열교환기',dlc:'직접 액체 냉각',immersion:'액침 냉각'},serverCabling:{structured:'구조화 배선',p2p:'점대점'},leafSpineCabling:{structured:'구조화 배선',p2p:'점대점'}})){for(const opt of $(id)?.options||[])if(map[opt.value])opt.textContent=map[opt.value];}
    for(const [id,map] of Object.entries({topology:{clos3:'3단 Clos',single:'단일 ToR',dual:'이중 ToR'},systemId:{custom:'사용자 지정 서버 사양'}})){for(const opt of $(id)?.options||[])if(map[opt.value])opt.textContent=map[opt.value];}
    const move=(id,target,title)=>{const el=$(id)?.closest('section.panel');if(el){el.hidden=false;if(title&&el.querySelector('h2'))el.querySelector('h2').textContent=title;target.append(el)}};
    if($('engineering-audit'))panels.evidence.append($('engineering-audit'));move('fabricDetail',panels.optical,'포트·광 예산 감사');move('coverageGrid',panels.evidence,'설계 범위와 미포함 항목');move('productBody',panels.evidence,'계산 서버 프로파일');move('opticalGuideCards',panels.optical,'광 인터커넥트 참고');move('coolingSvg',panels.power);move('rackSvg',panels.power);
    const oldBom=$('bomBody')?.closest('section.panel');if(oldBom)oldBom.hidden=true;
    const notice=document.createElement('div');notice.id='statusNotice';notice.setAttribute('role','status');notice.setAttribute('aria-live','polite');result.prepend(notice);
    $('targetPodEgress')?.closest('label')?.insertAdjacentHTML('beforeend','<small class="fieldHelp">Pod의 다운링크 대 업링크 대역폭 비율입니다. 4:1은 업링크 합계가 GPU 연결 대역폭의 1/4입니다.</small>');
    for(const id of ['serverDistanceM','leafSpineDistanceM'])$(id)?.closest('label')?.insertAdjacentHTML('beforeend','<small class="fieldHelp">입력 경로 길이입니다. 포설 여유와 트레이 실측 경로는 포함되지 않습니다.</small>');
    nav.querySelector('.jumpInput').onclick=()=>{ $('targetGPU').focus({preventScroll:true});form.scrollIntoView({behavior:'smooth',block:'start'}); };
    nav.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>activate(b.dataset.view));
    $('schedulePrev').onclick=()=>{page=Math.max(0,page-1);renderSchedule()};$('scheduleNext').onclick=()=>{page=Math.min(Math.ceil(allRoutes.length/80)-1,page+1);renderSchedule()};
    $('exportWorkbook').onclick=exportWorkbook;
    document.addEventListener('dc:design',e=>requestAnimationFrame(()=>render(e.detail||window.DCDesign)));
    document.addEventListener('dc:stale',stale);
    document.addEventListener('change',e=>{if(e.target.id==='wb-scenario'){const isColo=e.target.value==='colo';$('v65-mode').value=isColo?'colo':'ai';$('v65-mode').dispatchEvent(new Event('change',{bubbles:true}));$('targetGPU').closest('label').hidden=isColo;colo.open=isColo;stale();}if(e.target.closest('.formPanel input,.formPanel select'))stale();});
    document.addEventListener('click',e=>{if(e.target.matches('[data-lang]'))setTimeout(()=>{const s=$('run');if(s)s.textContent='계산 업데이트'},0)});
    if(window.DCDesign)render(window.DCDesign);
  }
  function activate(id){document.querySelectorAll('#workbench-nav [data-view]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.view===id)));for(const [key,p] of Object.entries(panels))p.hidden=key!==id;}
  function stale(){document.body.classList.add('design-stale');if($('statusNotice'))$('statusNotice').textContent='입력값이 변경되었습니다. 다시 계산하기 전까지 기존 결과는 이전 조건 기준입니다.';if($('exportWorkbook'))$('exportWorkbook').disabled=true;}
  function rackFor(index,r,role){let n=0;for(const x of r.racks||[])if(x.role===role){n+=Number(x.units)||0;if(index<=n)return x.id;}return '미배정';}
  function buildRoutes(r){allRoutes=[];const ports={};for(const [segment,o] of Object.entries(r.optical||{})){if(!o.links)continue;for(const q of (r.portAudit?.routes||[]).filter(x=>x.segment===segment)){const endpoint=(id)=>{const m=id.match(/(\d+)$/),i=Number(m?.[1]||0),server=id.startsWith('server-');return {name:server?'서버 '+i:id.replace(/-/g,' ').toUpperCase(),rack:server?rackFor(i,r,'Compute'):rackFor(i,r,'Network'),key:id};};const a=endpoint(q.a),b=endpoint(q.b),next=e=>{const k=segment+':'+e.key,n=(ports[k]||0)+1;ports[k]=n+q.links-1;return 'L'+n+'–L'+(n+q.links-1);};const cap=Math.floor(Number(r.input?.trunkFiberCount||0)/Number(o.trunk?.installedChannelFibers||Infinity));allRoutes.push({segment:{server:'서버–Leaf',leafSpine:'Leaf–Spine',core:'Spine–Core'}[segment]||segment,from:a.name,fromRack:a.rack,fromPort:next(a),to:b.name,toRack:b.rack,toPort:next(b),media:o.profile?.media||'미확정',connector:o.profile?.connector||'미확정',length:r.input?.[{server:'serverDistanceM',leafSpine:'leafSpineDistanceM',core:'coreDistanceM'}[segment]]??'—',links:q.links,active:o.profile?.optical?o.profile.fibers:0,installed:o.trunk?.installedChannelFibers||0,trunks:cap?Math.ceil(q.links/cap):0,loss:o.loss?.applicable?o.loss.estimatedDb+' / '+o.loss.budgetDb+' dB':'미적용'});}}page=0;renderSchedule();}
  function renderSchedule(){const rows=allRoutes.slice(page*80,page*80+80);$('scheduleBody').innerHTML=rows.map(x=>'<tr><td>'+esc(x.segment)+'</td><td><b>'+esc(x.from)+' · '+esc(x.fromPort)+'</b><small>'+esc(x.fromRack)+' → '+esc(x.to)+' · '+esc(x.toPort)+' · '+esc(x.toRack)+'</small></td><td>'+esc(x.media)+'<small>'+esc(x.connector)+'</small></td><td>'+esc(x.length)+' m</td><td>'+Number(x.links).toLocaleString()+'</td><td>'+x.active+' / '+x.installed+'</td><td>'+x.trunks+'</td><td>'+esc(x.loss)+'</td></tr>').join('');$('schedulePage').textContent=allRoutes.length?`${page*80+1}–${Math.min(page*80+80,allRoutes.length)} / ${allRoutes.length} 구간`:'계산 결과 대기';$('schedulePrev').disabled=page===0;$('scheduleNext').disabled=(page+1)*80>=allRoutes.length;}
  function sku(k){try{return JSON.parse(localStorage.getItem('dcBomSkuMap')||'{}')[k]||{sku:'',url:''}}catch{return{sku:'',url:''}}}
  function updateBom(r){const rows=r.bom||[];$('quoteBomBody').innerHTML=rows.map(x=>{const buy=Number(x.qty)||0;let install=Number(x.installedQty??buy)||0,spare=Number(x.spareQty)||0,known=Number.isFinite(Number(x.installedQty));if(x.category==='Connectivity'&&x.segment&&r.optical?.[x.segment]){const o=r.optical[x.segment];if(x.unit==='channel'){install=o.links*2;known=true}else if(x.unit==='trunk'){install=o.trunk.installedCableCount;known=true}else if(x.unit==='module'){install=o.installedModules;known=true}else if(x.unit==='assembly'){install=o.links;known=true}spare=Math.max(0,buy-install)}const verified=x.category==='Compute'&&Boolean(r.systemProfile?.source);return '<tr><td>'+esc(x.item)+'</td><td>'+esc(x.basis||'계산 결과')+'</td><td>'+install.toLocaleString()+'</td><td>'+spare.toLocaleString()+'</td><td><b>'+buy.toLocaleString()+' '+esc(x.unit)+'</b></td><td><span class="pill '+(verified?'ok':known?'review':'missing')+'">'+(verified?'프로파일 출처 확인':known?'산정값 · 제품 검토':'수량 분리 근거 없음')+'</span></td></tr>';}).join('');const kinds=[...new Set(rows.map(x=>x.category+' · '+x.item))];$('bomSummary').innerHTML='<div class="summaryCard"><span>BOM 항목</span><b>'+rows.length+'종</b><small>계산 결과 항목 수</small></div><div class="summaryCard"><span>제품코드 연결</span><b>미확인</b><small>공식 SKU DB 미연결</small></div><div class="summaryCard"><span>예비 정책</span><b>'+esc(r.input?.sparePct??'—')+'%</b><small>엔진 구매량 기준</small></div>';$('skuBody').innerHTML=kinds.map(k=>{const v=sku(k),safe=esc(k);return '<tr><td>'+safe+'</td><td>'+Number(rows.find(x=>x.category+' · '+x.item===k)?.qty||0).toLocaleString()+'</td><td><input class="skuInput" data-key="'+safe+'" aria-label="'+safe+' LS 품목코드" value="'+esc(v.sku)+'" placeholder="확인된 품목코드"></td><td><input class="skuUrl" data-key="'+safe+'" aria-label="'+safe+' 사양 URL" value="'+esc(v.url)+'" placeholder="공식 제품 사양 URL"></td><td><span class="pill missing">'+(v.sku&&v.url?'입력됨 · 검증 필요':'SKU 미연결')+'</span></td></tr>';}).join('');$('skuBody').querySelectorAll('input').forEach(el=>el.onchange=()=>{let data={};try{data=JSON.parse(localStorage.getItem('dcBomSkuMap')||'{}')}catch{}const k=el.dataset.key;data[k]??={sku:'',url:''};data[k][el.classList.contains('skuInput')?'sku':'url']=el.value.trim();localStorage.setItem('dcBomSkuMap',JSON.stringify(data));updateBom(r);});}
  function render(r){if(!r)return;latest=r;document.body.classList.remove('design-stale');$('exportWorkbook').disabled=!r.usable;$('statusNotice').textContent=r.usable?(r.status==='READY'?'계산 완료 · 제품·시공 검토 상태는 근거 탭에서 확인하세요.':'계산 완료 · 설계 결과 검토가 필요합니다.'):'계산 결과를 확인하세요.';if(r.usable)$('error').textContent='계획 산출입니다. 제품 사양·포트 브레이크아웃·광극성·PDU·냉각 및 시공 경로는 공급사와 현장 확인이 필요합니다.';buildRoutes(r);updateBom(r);if(r.racks){$('rackBody').innerHTML=r.racks.map(x=>'<tr><td>'+esc(x.id)+'</td><td>'+esc(x.role)+'</td><td>'+x.units+'</td><td>'+x.ru+'</td><td>'+x.powerKw+'</td><td>'+x.pduQty+'</td></tr>').join('');}if(r.facility){$('powerSummary').innerHTML='<div class="summaryCard"><span>IT 설계 부하</span><b>'+esc(r.summary.totalItPowerKw)+' kW</b><small>계산된 IT 부하</small></div><div class="summaryCard"><span>시설전력 시나리오</span><b>'+esc(r.facility.facilityPowerKw)+' kW</b><small>IT × PUE '+esc(r.facility.pue)+'</small></div><div class="summaryCard"><span>전체 랙</span><b>'+esc(r.summary.totalRacks)+'</b><small>계산 결과</small></div>';$('facilityPanel').innerHTML='<div class="summaryStrip"><div class="summaryCard"><span>UPS 용량</span><b>'+esc(r.facility.upsDesignKw)+' kW</b></div><div class="summaryCard"><span>발전기 용량</span><b>'+esc(r.facility.generatorDesignKw)+' kW</b></div><div class="summaryCard"><span>변압기 용량</span><b>'+esc(r.facility.transformerDesignKva)+' kVA</b></div></div><p>'+esc(r.facility.basis||'계산 가정은 상세 입력과 검토 근거를 확인하세요.')+'</p>';}const active=Object.entries(r.optical||{}).filter(([,o])=>o.links);$('cable-summary').innerHTML=active.map(([k,o])=>'<div class="summaryCard"><span>'+esc(({server:'서버–Leaf',leafSpine:'Leaf–Spine',core:'Spine–Core'})[k]||k)+'</span><b>'+Number(o.links).toLocaleString()+' 링크</b><small>'+esc(o.profile?.media)+' · '+(o.profile?.fibers||0)+' active / '+(o.trunk?.installedChannelFibers||0)+' installed F · '+(o.trunk?.installedCableCount||0).toLocaleString()+' 트렁크</small></div>').join('');const profile=r.systemProfile||{};$('sourceCard').innerHTML='<section class="panel"><h2>계산 근거·검토 상태</h2><div class="sourceRef"><b>서버 프로파일</b><span>'+esc(profile.name||r.summary?.system||'콜로케이션 용량 계획')+' · '+esc(profile.evidence||'가정 입력 기반')+'</span>'+(profile.source?'<a href="'+esc(profile.source)+'" target="_blank" rel="noopener">서버 사양 출처</a>':'<span class="pill review">출처 검증 필요</span>')+'</div><div class="sourceRef"><b>스위치·광모듈</b><span>SKU, firmware, cage/breakout, 커넥터와 극성 호환 확인 필요</span><span class="pill review">검토 필요</span></div><div class="sourceRef"><b>LS 제품 사양</b><span>품목코드·기계 사양·시험 데이터베이스 미연결</span><span class="pill missing">미연결</span></div><div class="sourceRef"><b>경로 범위</b><span>입력 길이이며 현장 실측, slack, tray·riser 우회 미포함</span></div></section>';$('ls-product-data').innerHTML='<section class="panel"><h2>케이블 제품 데이터 상태</h2><div class="missingGrid">'+['광섬유 종류·등급','파장별 감쇠','외경·굽힘반경','허용 인장·압궤','난연 등급','커넥터·극성','최대 IL/RL','제품코드·길이','시험성적·검증일'].map(x=>'<div><span>'+x+'</span><b>미연결</b></div>').join('')+'</div></section>';}
  function exportWorkbook(){if(!latest?.usable||window.DCDesignStale)return;const requirements=[...document.querySelectorAll('.formPanel input,.formPanel select')].map(x=>({field:x.closest('label')?.innerText||x.id,value:x.type==='checkbox'?x.checked:x.value}));fetch('/api/export-xlsx',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:'7.4.1',language:document.documentElement.lang,requirements,design:latest})}).then(async res=>{if(!res.ok)throw new Error('Excel 생성에 실패했습니다.');const a=document.createElement('a'),url=URL.createObjectURL(await res.blob());a.href=url;a.download='LS-DataCenter-BOM-v7.4.1.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}).catch(err=>{$('statusNotice').textContent=err.message;});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build,{once:true});else build();
})();
